export interface SeedEventDefinition {
  sourceUrl: string;
  title: string;
  subtitle?: string;
  description: string;
  category: string;
  organizer?: string;
  venueName?: string;
  address?: string;
  neighborhood?: string;
  city: string;
  lat?: number;
  lon?: number;
  startTime: string;
  endTime?: string;
  timezone: string;
  priceMin?: number | null;
  priceMax?: number | null;
  currency?: string;
  minAge?: number;
  tags?: string[];
  imageUrl?: string | null;
  bookingUrl?: string | null;
  accessibility?: string[];
  sourceDomain: string;
}

function getDaysFromNow(days: number, hour: number = 20, minute: number = 0): string {
  const date = new Date();
  date.setDate(date.getDate() + days);
  date.setHours(hour, minute, 0, 0);
  return date.toISOString();
}

export const SEED_EVENTS_BY_CITY: Record<string, SeedEventDefinition[]> = {
  'New York': [
    // MUSIC
    {
      sourceUrl: 'https://citypass-seed.com/nyc/jazz-blue-note-1',
      title: 'Jazz Night at Blue Note',
      subtitle: 'Featuring Grammy Award Winners',
      description: 'Experience world-class jazz in an intimate setting with acclaimed musicians from around the globe. Tonight features a special tribute to Miles Davis with a modern twist.',
      category: 'MUSIC',
      organizer: 'Blue Note Jazz Club',
      venueName: 'Blue Note Jazz Club',
      address: '131 W 3rd St, New York, NY 10012',
      neighborhood: 'Greenwich Village',
      city: 'New York',
      lat: 40.7305,
      lon: -74.0001,
      startTime: getDaysFromNow(2, 20, 0),
      endTime: getDaysFromNow(2, 22, 30),
      timezone: 'America/New_York',
      priceMin: 45,
      priceMax: 75,
      currency: 'USD',
      minAge: 21,
      tags: ['jazz', 'music', 'live', 'intimate'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/jazz-blue-note',
      accessibility: ['wheelchair-accessible', '21+'],
      sourceDomain: 'citypass-seed.com',
    },
    {
      sourceUrl: 'https://citypass-seed.com/nyc/live-nation-bowery-1',
      title: 'Indie Rock Showcase at Bowery Ballroom',
      subtitle: 'Rising Stars of Brooklyn Music Scene',
      description: 'Three up-and-coming indie rock bands take the stage at this iconic Lower East Side venue. Early show, all ages welcome.',
      category: 'MUSIC',
      organizer: 'Bowery Presents',
      venueName: 'Bowery Ballroom',
      address: '6 Delancey St, New York, NY 10002',
      neighborhood: 'Lower East Side',
      city: 'New York',
      lat: 40.7187,
      lon: -73.9938,
      startTime: getDaysFromNow(5, 19, 0),
      endTime: getDaysFromNow(5, 22, 0),
      timezone: 'America/New_York',
      priceMin: 20,
      priceMax: 25,
      currency: 'USD',
      tags: ['indie', 'rock', 'live-music', 'all-ages'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/bowery-indie',
      accessibility: ['all-ages', 'standing-room'],
      sourceDomain: 'citypass-seed.com',
    },
    {
      sourceUrl: 'https://citypass-seed.com/nyc/brooklyn-steel-electronic',
      title: 'Electronic Music Night at Brooklyn Steel',
      subtitle: 'Techno & House DJs',
      description: 'Dance the night away with internationally acclaimed DJs spinning techno, house, and deep electronic beats. State-of-the-art sound system and lighting.',
      category: 'MUSIC',
      organizer: 'Brooklyn Steel',
      venueName: 'Brooklyn Steel',
      address: '319 Frost St, Brooklyn, NY 11222',
      neighborhood: 'East Williamsburg',
      city: 'New York',
      lat: 40.7185,
      lon: -73.9363,
      startTime: getDaysFromNow(7, 22, 0),
      endTime: getDaysFromNow(8, 3, 0),
      timezone: 'America/New_York',
      priceMin: 30,
      priceMax: 50,
      currency: 'USD',
      minAge: 21,
      tags: ['electronic', 'techno', 'house', 'dance', 'nightlife'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/brooklyn-steel',
      accessibility: ['21+', 'wheelchair-accessible'],
      sourceDomain: 'citypass-seed.com',
    },
    {
      sourceUrl: 'https://citypass-seed.com/nyc/carnegie-hall-classical',
      title: 'New York Philharmonic at Carnegie Hall',
      subtitle: 'Tchaikovsky Symphony No. 5',
      description: 'A breathtaking evening of classical music featuring Tchaikovsky\'s Fifth Symphony, conducted by renowned maestro Gustavo Dudamel.',
      category: 'MUSIC',
      organizer: 'Carnegie Hall',
      venueName: 'Carnegie Hall',
      address: '881 7th Ave, New York, NY 10019',
      neighborhood: 'Midtown',
      city: 'New York',
      lat: 40.7651,
      lon: -73.9799,
      startTime: getDaysFromNow(10, 19, 30),
      endTime: getDaysFromNow(10, 21, 30),
      timezone: 'America/New_York',
      priceMin: 75,
      priceMax: 250,
      currency: 'USD',
      tags: ['classical', 'orchestra', 'symphony', 'elegant'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/carnegie',
      accessibility: ['wheelchair-accessible', 'formal-attire'],
      sourceDomain: 'citypass-seed.com',
    },

    // COMEDY
    {
      sourceUrl: 'https://citypass-seed.com/nyc/comedy-cellar-1',
      title: 'Comedy Night at Comedy Cellar',
      subtitle: 'Live Stand-Up Comedy',
      description: 'An unforgettable night of laughter with top NYC comedians. Surprise guests often include SNL cast members and Netflix special headliners.',
      category: 'COMEDY',
      organizer: 'Comedy Cellar',
      venueName: 'Comedy Cellar',
      address: '117 MacDougal St, New York, NY 10012',
      neighborhood: 'Greenwich Village',
      city: 'New York',
      lat: 40.7298,
      lon: -74.001,
      startTime: getDaysFromNow(1, 21, 0),
      endTime: getDaysFromNow(1, 23, 30),
      timezone: 'America/New_York',
      priceMin: 20,
      priceMax: 30,
      currency: 'USD',
      tags: ['comedy', 'stand-up', 'entertainment', 'nightlife'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/comedy-cellar',
      accessibility: ['wheelchair-accessible'],
      sourceDomain: 'citypass-seed.com',
    },
    {
      sourceUrl: 'https://citypass-seed.com/nyc/ucb-improv',
      title: 'Improv Comedy at UCB Theatre',
      subtitle: 'Long-Form Improv Show',
      description: 'The legendary Upright Citizens Brigade presents an evening of hilarious long-form improv. Every show is completely unique and unscripted.',
      category: 'COMEDY',
      organizer: 'UCB Theatre',
      venueName: 'UCB Theatre',
      address: '307 W 26th St, New York, NY 10001',
      neighborhood: 'Chelsea',
      city: 'New York',
      lat: 40.7489,
      lon: -73.9968,
      startTime: getDaysFromNow(4, 20, 0),
      endTime: getDaysFromNow(4, 21, 30),
      timezone: 'America/New_York',
      priceMin: 10,
      priceMax: 15,
      currency: 'USD',
      tags: ['comedy', 'improv', 'sketch', 'interactive'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/ucb',
      accessibility: ['affordable', 'intimate-venue'],
      sourceDomain: 'citypass-seed.com',
    },

    // THEATRE
    {
      sourceUrl: 'https://citypass-seed.com/nyc/hamilton-broadway',
      title: 'Hamilton on Broadway',
      subtitle: 'The Award-Winning Musical',
      description: 'The story of American founding father Alexander Hamilton, told through a revolutionary blend of hip-hop, jazz, R&B, and Broadway. Winner of 11 Tony Awards.',
      category: 'THEATRE',
      organizer: 'Broadway LLC',
      venueName: 'Richard Rodgers Theatre',
      address: '226 W 46th St, New York, NY 10036',
      neighborhood: 'Theater District',
      city: 'New York',
      lat: 40.759,
      lon: -73.9872,
      startTime: getDaysFromNow(6, 20, 0),
      endTime: getDaysFromNow(6, 22, 45),
      timezone: 'America/New_York',
      priceMin: 99,
      priceMax: 399,
      currency: 'USD',
      tags: ['broadway', 'musical', 'theatre', 'award-winning'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/hamilton',
      accessibility: ['wheelchair-accessible'],
      sourceDomain: 'citypass-seed.com',
    },
    {
      sourceUrl: 'https://citypass-seed.com/nyc/off-broadway-drama',
      title: 'New American Play at Playwrights Horizons',
      subtitle: 'Off-Broadway Drama Premiere',
      description: 'World premiere of an intimate drama exploring modern relationships and identity. Limited engagement by acclaimed playwright.',
      category: 'THEATRE',
      organizer: 'Playwrights Horizons',
      venueName: 'Playwrights Horizons',
      address: '416 W 42nd St, New York, NY 10036',
      neighborhood: 'Hell\'s Kitchen',
      city: 'New York',
      lat: 40.7580,
      lon: -73.9896,
      startTime: getDaysFromNow(8, 19, 30),
      endTime: getDaysFromNow(8, 21, 30),
      timezone: 'America/New_York',
      priceMin: 45,
      priceMax: 85,
      currency: 'USD',
      tags: ['off-broadway', 'drama', 'new-play', 'intimate'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/playwrights',
      accessibility: ['wheelchair-accessible', 'intimate-theatre'],
      sourceDomain: 'citypass-seed.com',
    },

    // FITNESS
    {
      sourceUrl: 'https://citypass-seed.com/nyc/central-park-yoga',
      title: 'Free Morning Yoga in Central Park',
      subtitle: 'All Levels Welcome',
      description: 'Start your day with a rejuvenating yoga session in beautiful Central Park. Bring your own mat and enjoy the sunrise with the NYC yoga community.',
      category: 'FITNESS',
      organizer: 'NYC Parks & Recreation',
      venueName: 'Central Park - Sheep Meadow',
      address: 'Central Park, New York, NY 10024',
      neighborhood: 'Upper West Side',
      city: 'New York',
      lat: 40.7749,
      lon: -73.9732,
      startTime: getDaysFromNow(3, 8, 0),
      endTime: getDaysFromNow(3, 9, 0),
      timezone: 'America/New_York',
      priceMin: 0,
      priceMax: 0,
      currency: 'USD',
      tags: ['yoga', 'fitness', 'free', 'outdoor', 'wellness'],
      imageUrl: null,
      bookingUrl: null,
      accessibility: ['outdoor', 'free', 'all-levels'],
      sourceDomain: 'citypass-seed.com',
    },
    {
      sourceUrl: 'https://citypass-seed.com/nyc/brooklyn-bridge-run',
      title: 'Brooklyn Bridge 10K Run',
      subtitle: 'Charity Running Event',
      description: 'Run across the iconic Brooklyn Bridge and through DUMBO. All proceeds benefit NYC youth athletics programs. Free t-shirt included.',
      category: 'FITNESS',
      organizer: 'NYRR',
      venueName: 'Brooklyn Bridge Park',
      address: 'Brooklyn Bridge Park, Brooklyn, NY 11201',
      neighborhood: 'DUMBO',
      city: 'New York',
      lat: 40.7024,
      lon: -73.9875,
      startTime: getDaysFromNow(9, 7, 0),
      endTime: getDaysFromNow(9, 10, 0),
      timezone: 'America/New_York',
      priceMin: 35,
      priceMax: 35,
      currency: 'USD',
      tags: ['running', '10k', 'fitness', 'charity', 'outdoor'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/brooklyn-10k',
      accessibility: ['outdoor', 'all-levels'],
      sourceDomain: 'citypass-seed.com',
    },

    // DANCE
    {
      sourceUrl: 'https://citypass-seed.com/nyc/alvin-ailey-ballet',
      title: 'Alvin Ailey American Dance Theater',
      subtitle: 'Contemporary Dance Performance',
      description: 'World-renowned dance company performs stunning contemporary and modern dance. Tonight features the iconic "Revelations" and new original works.',
      category: 'DANCE',
      organizer: 'Alvin Ailey',
      venueName: 'New York City Center',
      address: '131 W 55th St, New York, NY 10019',
      neighborhood: 'Midtown',
      city: 'New York',
      lat: 40.7649,
      lon: -73.9810,
      startTime: getDaysFromNow(11, 19, 30),
      endTime: getDaysFromNow(11, 21, 30),
      timezone: 'America/New_York',
      priceMin: 55,
      priceMax: 150,
      currency: 'USD',
      tags: ['dance', 'modern-dance', 'ballet', 'performance-art'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/alvin-ailey',
      accessibility: ['wheelchair-accessible'],
      sourceDomain: 'citypass-seed.com',
    },
    {
      sourceUrl: 'https://citypass-seed.com/nyc/salsa-lessons',
      title: 'Salsa Dancing Lessons & Social',
      subtitle: 'Beginner-Friendly Latin Dance',
      description: 'Learn salsa basics in a fun, welcoming environment, then practice your new moves at our social dance party. No partner required!',
      category: 'DANCE',
      organizer: 'Dance Manhattan',
      venueName: 'Dance Manhattan',
      address: '39 W 19th St, New York, NY 10011',
      neighborhood: 'Flatiron',
      city: 'New York',
      lat: 40.7395,
      lon: -73.9929,
      startTime: getDaysFromNow(4, 19, 0),
      endTime: getDaysFromNow(4, 22, 0),
      timezone: 'America/New_York',
      priceMin: 20,
      priceMax: 20,
      currency: 'USD',
      tags: ['salsa', 'dance', 'lessons', 'social', 'beginner-friendly'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/salsa',
      accessibility: ['beginner-friendly', 'no-partner-required'],
      sourceDomain: 'citypass-seed.com',
    },

    // ARTS
    {
      sourceUrl: 'https://citypass-seed.com/nyc/moma-modern-art',
      title: 'Modern Art Exhibition at MoMA',
      subtitle: 'Contemporary Masters Collection',
      description: 'Explore groundbreaking works from modern artists including Picasso, Warhol, and emerging contemporary voices. Special exhibition runs through the month.',
      category: 'ARTS',
      organizer: 'Museum of Modern Art',
      venueName: 'MoMA',
      address: '11 W 53rd St, New York, NY 10019',
      neighborhood: 'Midtown',
      city: 'New York',
      lat: 40.7614,
      lon: -73.9776,
      startTime: getDaysFromNow(5, 10, 0),
      endTime: getDaysFromNow(5, 17, 30),
      timezone: 'America/New_York',
      priceMin: 25,
      priceMax: 25,
      currency: 'USD',
      tags: ['art', 'museum', 'exhibition', 'modern-art'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/moma',
      accessibility: ['wheelchair-accessible', 'indoor'],
      sourceDomain: 'citypass-seed.com',
    },
    {
      sourceUrl: 'https://citypass-seed.com/nyc/whitney-contemporary',
      title: 'Whitney Biennial Contemporary Art',
      subtitle: 'Cutting-Edge American Art',
      description: 'The Whitney Museum\'s flagship exhibition showcasing the most provocative and innovative work by contemporary American artists.',
      category: 'ARTS',
      organizer: 'Whitney Museum',
      venueName: 'Whitney Museum of American Art',
      address: '99 Gansevoort St, New York, NY 10014',
      neighborhood: 'Meatpacking District',
      city: 'New York',
      lat: 40.7396,
      lon: -74.0089,
      startTime: getDaysFromNow(7, 10, 30),
      endTime: getDaysFromNow(7, 18, 0),
      timezone: 'America/New_York',
      priceMin: 25,
      priceMax: 25,
      currency: 'USD',
      tags: ['art', 'contemporary', 'museum', 'biennial'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/whitney',
      accessibility: ['wheelchair-accessible', 'indoor'],
      sourceDomain: 'citypass-seed.com',
    },
    {
      sourceUrl: 'https://citypass-seed.com/nyc/gallery-opening-chelsea',
      title: 'Contemporary Art Gallery Opening',
      subtitle: 'New Artist Showcase in Chelsea',
      description: 'Free wine and cheese reception for the opening of a new contemporary art exhibition featuring emerging NYC artists. Meet the artists!',
      category: 'ARTS',
      organizer: 'Gagosian Gallery',
      venueName: 'Gagosian Gallery Chelsea',
      address: '555 W 24th St, New York, NY 10011',
      neighborhood: 'Chelsea',
      city: 'New York',
      lat: 40.7493,
      lon: -74.0062,
      startTime: getDaysFromNow(2, 18, 0),
      endTime: getDaysFromNow(2, 21, 0),
      timezone: 'America/New_York',
      priceMin: 0,
      priceMax: 0,
      currency: 'USD',
      tags: ['art', 'gallery', 'free', 'opening-reception', 'wine'],
      imageUrl: null,
      bookingUrl: null,
      accessibility: ['free', 'wheelchair-accessible', 'networking'],
      sourceDomain: 'citypass-seed.com',
    },

    // FOOD
    {
      sourceUrl: 'https://citypass-seed.com/nyc/brooklyn-food-festival',
      title: 'Brooklyn Food & Wine Festival',
      subtitle: 'Taste the Best of Brooklyn',
      description: 'Sample dishes from 50+ local restaurants and food vendors. Features craft beer garden, wine tastings, and live cooking demonstrations by celebrity chefs.',
      category: 'FOOD',
      organizer: 'Brooklyn Tourism',
      venueName: 'Brooklyn Bridge Park',
      address: 'Brooklyn Bridge Park, Brooklyn, NY 11201',
      neighborhood: 'DUMBO',
      city: 'New York',
      lat: 40.7024,
      lon: -73.9875,
      startTime: getDaysFromNow(12, 12, 0),
      endTime: getDaysFromNow(12, 19, 0),
      timezone: 'America/New_York',
      priceMin: 35,
      priceMax: 35,
      currency: 'USD',
      tags: ['food', 'wine', 'festival', 'outdoor', 'tasting'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/brooklyn-food',
      accessibility: ['outdoor', 'family-friendly'],
      sourceDomain: 'citypass-seed.com',
    },
    {
      sourceUrl: 'https://citypass-seed.com/nyc/ramen-masterclass',
      title: 'Authentic Ramen Making Class',
      subtitle: 'Learn from Master Chef',
      description: 'Hands-on class teaching you to make authentic Japanese ramen from scratch, including noodles, broth, and toppings. Take home recipes and techniques.',
      category: 'FOOD',
      organizer: 'Institute of Culinary Education',
      venueName: 'ICE',
      address: '225 Liberty St, New York, NY 10281',
      neighborhood: 'Financial District',
      city: 'New York',
      lat: 40.7130,
      lon: -74.0154,
      startTime: getDaysFromNow(6, 18, 30),
      endTime: getDaysFromNow(6, 21, 0),
      timezone: 'America/New_York',
      priceMin: 95,
      priceMax: 95,
      currency: 'USD',
      tags: ['food', 'cooking-class', 'ramen', 'japanese', 'hands-on'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/ramen-class',
      accessibility: ['indoor', 'hands-on'],
      sourceDomain: 'citypass-seed.com',
    },
    {
      sourceUrl: 'https://citypass-seed.com/nyc/smorgasburg-market',
      title: 'Smorgasburg Food Market',
      subtitle: 'NYC\'s Largest Weekly Food Market',
      description: 'Over 100 food vendors offering unique dishes from around the world. Perfect for foodies looking to discover new flavors. Open-air market with waterfront views.',
      category: 'FOOD',
      organizer: 'Smorgasburg',
      venueName: 'Williamsburg Waterfront',
      address: '90 Kent Ave, Brooklyn, NY 11249',
      neighborhood: 'Williamsburg',
      city: 'New York',
      lat: 40.7195,
      lon: -73.9637,
      startTime: getDaysFromNow(3, 11, 0),
      endTime: getDaysFromNow(3, 18, 0),
      timezone: 'America/New_York',
      priceMin: 0,
      priceMax: 0,
      currency: 'USD',
      tags: ['food', 'market', 'free-entry', 'outdoor', 'street-food'],
      imageUrl: null,
      bookingUrl: null,
      accessibility: ['free', 'outdoor', 'family-friendly'],
      sourceDomain: 'citypass-seed.com',
    },

    // NETWORKING
    {
      sourceUrl: 'https://citypass-seed.com/nyc/tech-meetup',
      title: 'NYC Tech Startup Mixer',
      subtitle: 'Network with Founders & Investors',
      description: 'Monthly networking event for tech professionals, startup founders, and investors. Includes lightning talks from successful founders and open networking.',
      category: 'NETWORKING',
      organizer: 'NY Tech Meetup',
      venueName: 'WeWork SoHo',
      address: '110 Greene St, New York, NY 10012',
      neighborhood: 'SoHo',
      city: 'New York',
      lat: 40.7247,
      lon: -74.0026,
      startTime: getDaysFromNow(5, 18, 30),
      endTime: getDaysFromNow(5, 21, 0),
      timezone: 'America/New_York',
      priceMin: 15,
      priceMax: 15,
      currency: 'USD',
      tags: ['networking', 'tech', 'startup', 'business', 'professional'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/tech-mixer',
      accessibility: ['wheelchair-accessible', 'business-casual'],
      sourceDomain: 'citypass-seed.com',
    },
    {
      sourceUrl: 'https://citypass-seed.com/nyc/creative-brunch',
      title: 'Creative Professionals Brunch',
      subtitle: 'Network Over Breakfast',
      description: 'Connect with fellow designers, artists, writers, and creatives over brunch. Casual networking in a relaxed environment. Coffee and pastries provided.',
      category: 'NETWORKING',
      organizer: 'Creative Mornings NYC',
      venueName: 'The Wing SoHo',
      address: '52 Mercer St, New York, NY 10013',
      neighborhood: 'SoHo',
      city: 'New York',
      lat: 40.7229,
      lon: -74.0008,
      startTime: getDaysFromNow(8, 9, 30),
      endTime: getDaysFromNow(8, 11, 30),
      timezone: 'America/New_York',
      priceMin: 0,
      priceMax: 0,
      currency: 'USD',
      tags: ['networking', 'creative', 'brunch', 'free', 'casual'],
      imageUrl: null,
      bookingUrl: null,
      accessibility: ['free', 'casual', 'morning-event'],
      sourceDomain: 'citypass-seed.com',
    },

    // FAMILY
    {
      sourceUrl: 'https://citypass-seed.com/nyc/puppet-show',
      title: 'Interactive Puppet Show for Kids',
      subtitle: 'Family-Friendly Entertainment',
      description: 'Delightful puppet show featuring classic fairy tales brought to life. Interactive segments encourage kids to participate. Perfect for ages 3-10.',
      category: 'FAMILY',
      organizer: 'Swedish Cottage Marionette Theatre',
      venueName: 'Swedish Cottage Theatre',
      address: 'Central Park West & 79th St, New York, NY 10024',
      neighborhood: 'Upper West Side',
      city: 'New York',
      lat: 40.7772,
      lon: -73.9738,
      startTime: getDaysFromNow(4, 14, 0),
      endTime: getDaysFromNow(4, 15, 0),
      timezone: 'America/New_York',
      priceMin: 12,
      priceMax: 12,
      currency: 'USD',
      tags: ['family', 'kids', 'puppet-show', 'interactive', 'educational'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/puppets',
      accessibility: ['family-friendly', 'wheelchair-accessible'],
      sourceDomain: 'citypass-seed.com',
    },
    {
      sourceUrl: 'https://citypass-seed.com/nyc/childrens-museum',
      title: 'Interactive Science Day at Children\'s Museum',
      subtitle: 'Hands-On STEM Learning',
      description: 'Special science-themed day with interactive exhibits, live demonstrations, and hands-on experiments. Kids learn about physics, chemistry, and biology through play.',
      category: 'FAMILY',
      organizer: 'Children\'s Museum of Manhattan',
      venueName: 'CMOM',
      address: '212 W 83rd St, New York, NY 10024',
      neighborhood: 'Upper West Side',
      city: 'New York',
      lat: 40.7846,
      lon: -73.9754,
      startTime: getDaysFromNow(10, 10, 0),
      endTime: getDaysFromNow(10, 16, 0),
      timezone: 'America/New_York',
      priceMin: 18,
      priceMax: 18,
      currency: 'USD',
      tags: ['family', 'kids', 'museum', 'science', 'educational', 'interactive'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/science-day',
      accessibility: ['family-friendly', 'wheelchair-accessible', 'educational'],
      sourceDomain: 'citypass-seed.com',
    },

    // OTHER
    {
      sourceUrl: 'https://citypass-seed.com/nyc/trivia-night',
      title: 'Pub Trivia Night at Irish Pub',
      subtitle: 'Test Your Knowledge',
      description: 'Weekly trivia night with cash prizes for winning teams. Themed rounds include pop culture, history, sports, and NYC facts. Free to play, food and drink specials.',
      category: 'OTHER',
      organizer: 'McGee\'s Pub',
      venueName: 'McGee\'s Pub',
      address: '240 W 55th St, New York, NY 10019',
      neighborhood: 'Midtown West',
      city: 'New York',
      lat: 40.7656,
      lon: -73.9845,
      startTime: getDaysFromNow(1, 20, 0),
      endTime: getDaysFromNow(1, 22, 30),
      timezone: 'America/New_York',
      priceMin: 0,
      priceMax: 0,
      currency: 'USD',
      tags: ['trivia', 'pub', 'social', 'free', 'weekly'],
      imageUrl: null,
      bookingUrl: null,
      accessibility: ['free', 'team-activity', 'casual'],
      sourceDomain: 'citypass-seed.com',
    },
    {
      sourceUrl: 'https://citypass-seed.com/nyc/book-club',
      title: 'Open Book Club Discussion',
      subtitle: 'Community Literary Gathering',
      description: 'Monthly book club meeting open to all readers. This month: contemporary fiction. Friendly discussion led by local librarian. Coffee and cookies provided.',
      category: 'OTHER',
      organizer: 'Housing Works Bookstore',
      venueName: 'Housing Works Bookstore Cafe',
      address: '126 Crosby St, New York, NY 10012',
      neighborhood: 'SoHo',
      city: 'New York',
      lat: 40.7233,
      lon: -73.9985,
      startTime: getDaysFromNow(9, 19, 0),
      endTime: getDaysFromNow(9, 21, 0),
      timezone: 'America/New_York',
      priceMin: 0,
      priceMax: 0,
      currency: 'USD',
      tags: ['books', 'literary', 'discussion', 'community', 'free'],
      imageUrl: null,
      bookingUrl: null,
      accessibility: ['free', 'intellectual', 'casual'],
      sourceDomain: 'citypass-seed.com',
    },
  ],

  'San Francisco': [
    // MUSIC
    {
      sourceUrl: 'https://citypass-seed.com/sf/jazz-festival',
      title: 'SF Jazz Festival at SFJAZZ Center',
      subtitle: 'Annual Jazz Celebration',
      description: 'Three days of world-class jazz performances featuring legendary artists and rising stars. Tonight\'s lineup includes Grammy winners and jazz innovators.',
      category: 'MUSIC',
      organizer: 'SFJAZZ',
      venueName: 'SFJAZZ Center',
      address: '201 Franklin St, San Francisco, CA 94102',
      neighborhood: 'Hayes Valley',
      city: 'San Francisco',
      lat: 37.7765,
      lon: -122.4216,
      startTime: getDaysFromNow(3, 19, 0),
      endTime: getDaysFromNow(3, 22, 0),
      timezone: 'America/Los_Angeles',
      priceMin: 45,
      priceMax: 95,
      currency: 'USD',
      tags: ['jazz', 'festival', 'music', 'world-class'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/sf-jazz',
      accessibility: ['wheelchair-accessible'],
      sourceDomain: 'citypass-seed.com',
    },
    {
      sourceUrl: 'https://citypass-seed.com/sf/fillmore-indie',
      title: 'Indie Band Night at The Fillmore',
      subtitle: 'Historic Venue Showcase',
      description: 'Experience live music at the legendary Fillmore. Tonight features three indie rock bands in the iconic venue that hosted Janis Joplin and The Grateful Dead.',
      category: 'MUSIC',
      organizer: 'Live Nation',
      venueName: 'The Fillmore',
      address: '1805 Geary Blvd, San Francisco, CA 94115',
      neighborhood: 'Fillmore District',
      city: 'San Francisco',
      lat: 37.7841,
      lon: -122.4330,
      startTime: getDaysFromNow(5, 20, 0),
      endTime: getDaysFromNow(5, 23, 0),
      timezone: 'America/Los_Angeles',
      priceMin: 30,
      priceMax: 45,
      currency: 'USD',
      tags: ['indie', 'rock', 'live-music', 'historic-venue'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/fillmore',
      accessibility: ['21+', 'standing-room'],
      sourceDomain: 'citypass-seed.com',
    },
    {
      sourceUrl: 'https://citypass-seed.com/sf/symphony-hall',
      title: 'San Francisco Symphony: Mahler\'s 5th',
      subtitle: 'Classical Music Performance',
      description: 'The SF Symphony performs Mahler\'s Fifth Symphony, one of the most powerful works in the orchestral repertoire. Conducted by music director Esa-Pekka Salonen.',
      category: 'MUSIC',
      organizer: 'SF Symphony',
      venueName: 'Davies Symphony Hall',
      address: '201 Van Ness Ave, San Francisco, CA 94102',
      neighborhood: 'Civic Center',
      city: 'San Francisco',
      lat: 37.7783,
      lon: -122.4200,
      startTime: getDaysFromNow(8, 19, 30),
      endTime: getDaysFromNow(8, 21, 30),
      timezone: 'America/Los_Angeles',
      priceMin: 60,
      priceMax: 200,
      currency: 'USD',
      tags: ['classical', 'orchestra', 'symphony', 'mahler'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/sf-symphony',
      accessibility: ['wheelchair-accessible', 'formal-attire'],
      sourceDomain: 'citypass-seed.com',
    },

    // COMEDY
    {
      sourceUrl: 'https://citypass-seed.com/sf/punchline-comedy',
      title: 'Stand-Up Comedy at Punchline',
      subtitle: 'Top Bay Area Comedians',
      description: 'Laugh out loud with the Bay Area\'s funniest comedians. Tonight\'s lineup includes Netflix specials and late-night TV regulars. Two-drink minimum.',
      category: 'COMEDY',
      organizer: 'Punchline SF',
      venueName: 'Punchline Comedy Club',
      address: '444 Battery St, San Francisco, CA 94111',
      neighborhood: 'Financial District',
      city: 'San Francisco',
      lat: 37.7950,
      lon: -122.4003,
      startTime: getDaysFromNow(2, 20, 0),
      endTime: getDaysFromNow(2, 22, 0),
      timezone: 'America/Los_Angeles',
      priceMin: 25,
      priceMax: 35,
      currency: 'USD',
      minAge: 18,
      tags: ['comedy', 'stand-up', 'nightlife'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/punchline',
      accessibility: ['18+', 'two-drink-minimum'],
      sourceDomain: 'citypass-seed.com',
    },

    // FOOD
    {
      sourceUrl: 'https://citypass-seed.com/sf/food-tour',
      title: 'Mission District Food Tour',
      subtitle: 'Taste of San Francisco',
      description: 'Explore the best tacos, burritos, and street food in the Mission. Walking tour includes 6 food stops plus historical and cultural insights from expert guide.',
      category: 'FOOD',
      organizer: 'SF Food Tours',
      venueName: 'Mission District',
      address: 'Mission St & 16th St, San Francisco, CA 94110',
      neighborhood: 'Mission',
      city: 'San Francisco',
      lat: 37.7647,
      lon: -122.4194,
      startTime: getDaysFromNow(6, 11, 0),
      endTime: getDaysFromNow(6, 14, 0),
      timezone: 'America/Los_Angeles',
      priceMin: 75,
      priceMax: 75,
      currency: 'USD',
      tags: ['food', 'tour', 'mexican', 'walking-tour', 'street-food'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/sf-food-tour',
      accessibility: ['walking-required'],
      sourceDomain: 'citypass-seed.com',
    },
    {
      sourceUrl: 'https://citypass-seed.com/sf/ferry-building-market',
      title: 'Ferry Building Farmers Market',
      subtitle: 'Local & Organic Produce',
      description: 'Renowned farmers market featuring the Bay Area\'s finest organic produce, artisan foods, and specialty products. Free entry, live music, and chef demonstrations.',
      category: 'FOOD',
      organizer: 'CUESA',
      venueName: 'Ferry Building Marketplace',
      address: '1 Ferry Building, San Francisco, CA 94111',
      neighborhood: 'Embarcadero',
      city: 'San Francisco',
      lat: 37.7955,
      lon: -122.3937,
      startTime: getDaysFromNow(3, 10, 0),
      endTime: getDaysFromNow(3, 14, 0),
      timezone: 'America/Los_Angeles',
      priceMin: 0,
      priceMax: 0,
      currency: 'USD',
      tags: ['farmers-market', 'organic', 'local', 'free', 'food'],
      imageUrl: null,
      bookingUrl: null,
      accessibility: ['free', 'outdoor', 'family-friendly'],
      sourceDomain: 'citypass-seed.com',
    },
    {
      sourceUrl: 'https://citypass-seed.com/sf/dim-sum-workshop',
      title: 'Dim Sum Making Workshop',
      subtitle: 'Learn Traditional Techniques',
      description: 'Master the art of making authentic dim sum with an expert Chinatown chef. Hands-on class includes dumplings, bao, and spring rolls. Take home recipes and skills.',
      category: 'FOOD',
      organizer: 'SF Cooking School',
      venueName: 'SF Cooking School',
      address: '690 Van Ness Ave, San Francisco, CA 94102',
      neighborhood: 'Civic Center',
      city: 'San Francisco',
      lat: 37.7818,
      lon: -122.4207,
      startTime: getDaysFromNow(9, 18, 0),
      endTime: getDaysFromNow(9, 21, 0),
      timezone: 'America/Los_Angeles',
      priceMin: 85,
      priceMax: 85,
      currency: 'USD',
      tags: ['cooking-class', 'dim-sum', 'chinese', 'hands-on'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/dim-sum',
      accessibility: ['hands-on', 'indoor'],
      sourceDomain: 'citypass-seed.com',
    },

    // FITNESS
    {
      sourceUrl: 'https://citypass-seed.com/sf/bay-to-breakers',
      title: 'Bay to Breakers 12K Run',
      subtitle: 'SF\'s Legendary Running Event',
      description: 'Join thousands of runners in San Francisco\'s most iconic race. Run from the Bay to the Ocean through the heart of the city. Costumes encouraged!',
      category: 'FITNESS',
      organizer: 'Bay to Breakers',
      venueName: 'Embarcadero to Ocean Beach',
      address: 'Howard St & Embarcadero, San Francisco, CA 94105',
      neighborhood: 'Embarcadero',
      city: 'San Francisco',
      lat: 37.7895,
      lon: -122.3892,
      startTime: getDaysFromNow(14, 8, 0),
      endTime: getDaysFromNow(14, 12, 0),
      timezone: 'America/Los_Angeles',
      priceMin: 55,
      priceMax: 55,
      currency: 'USD',
      tags: ['running', '12k', 'fitness', 'iconic', 'fun-run'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/bay-to-breakers',
      accessibility: ['outdoor', 'costume-friendly'],
      sourceDomain: 'citypass-seed.com',
    },
    {
      sourceUrl: 'https://citypass-seed.com/sf/golden-gate-yoga',
      title: 'Sunrise Yoga at Crissy Field',
      subtitle: 'Golden Gate Bridge Views',
      description: 'Start your day with yoga overlooking the Golden Gate Bridge. All levels welcome. Bring your mat and enjoy the peaceful morning by the bay.',
      category: 'FITNESS',
      organizer: 'SF Parks Alliance',
      venueName: 'Crissy Field',
      address: '603 Mason St, San Francisco, CA 94129',
      neighborhood: 'Presidio',
      city: 'San Francisco',
      lat: 37.8054,
      lon: -122.4657,
      startTime: getDaysFromNow(4, 7, 0),
      endTime: getDaysFromNow(4, 8, 0),
      timezone: 'America/Los_Angeles',
      priceMin: 0,
      priceMax: 0,
      currency: 'USD',
      tags: ['yoga', 'free', 'outdoor', 'sunrise', 'wellness'],
      imageUrl: null,
      bookingUrl: null,
      accessibility: ['free', 'outdoor', 'all-levels'],
      sourceDomain: 'citypass-seed.com',
    },

    // ARTS
    {
      sourceUrl: 'https://citypass-seed.com/sf/sfmoma-contemporary',
      title: 'SFMOMA Contemporary Art Exhibition',
      subtitle: 'Modern & Contemporary Masterworks',
      description: 'Explore seven floors of modern and contemporary art, including works by Matisse, Warhol, and local Bay Area artists. Special exhibition on photography.',
      category: 'ARTS',
      organizer: 'SFMOMA',
      venueName: 'San Francisco Museum of Modern Art',
      address: '151 3rd St, San Francisco, CA 94103',
      neighborhood: 'SoMa',
      city: 'San Francisco',
      lat: 37.7857,
      lon: -122.4011,
      startTime: getDaysFromNow(5, 10, 0),
      endTime: getDaysFromNow(5, 17, 0),
      timezone: 'America/Los_Angeles',
      priceMin: 25,
      priceMax: 25,
      currency: 'USD',
      tags: ['art', 'museum', 'contemporary', 'modern-art'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/sfmoma',
      accessibility: ['wheelchair-accessible', 'indoor'],
      sourceDomain: 'citypass-seed.com',
    },
    {
      sourceUrl: 'https://citypass-seed.com/sf/asian-art-museum',
      title: 'Asian Art Museum: Ancient Treasures',
      subtitle: 'Explore 6,000 Years of Asian Art',
      description: 'One of the most comprehensive Asian art collections in the world. Special exhibition features ancient Chinese ceramics and Japanese woodblock prints.',
      category: 'ARTS',
      organizer: 'Asian Art Museum',
      venueName: 'Asian Art Museum',
      address: '200 Larkin St, San Francisco, CA 94102',
      neighborhood: 'Civic Center',
      city: 'San Francisco',
      lat: 37.7803,
      lon: -122.4161,
      startTime: getDaysFromNow(7, 10, 0),
      endTime: getDaysFromNow(7, 17, 0),
      timezone: 'America/Los_Angeles',
      priceMin: 15,
      priceMax: 15,
      currency: 'USD',
      tags: ['art', 'museum', 'asian-art', 'cultural'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/asian-art',
      accessibility: ['wheelchair-accessible', 'educational'],
      sourceDomain: 'citypass-seed.com',
    },

    // THEATRE
    {
      sourceUrl: 'https://citypass-seed.com/sf/orpheum-musical',
      title: 'Broadway Musical at Orpheum Theatre',
      subtitle: 'Touring Production of Wicked',
      description: 'The smash hit musical tells the untold story of the Witches of Oz. Spectacular sets, costumes, and music make this a must-see production.',
      category: 'THEATRE',
      organizer: 'SHN',
      venueName: 'Orpheum Theatre',
      address: '1192 Market St, San Francisco, CA 94102',
      neighborhood: 'Civic Center',
      city: 'San Francisco',
      lat: 37.7790,
      lon: -122.4134,
      startTime: getDaysFromNow(10, 19, 30),
      endTime: getDaysFromNow(10, 22, 0),
      timezone: 'America/Los_Angeles',
      priceMin: 75,
      priceMax: 250,
      currency: 'USD',
      tags: ['broadway', 'musical', 'theatre', 'wicked'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/wicked',
      accessibility: ['wheelchair-accessible'],
      sourceDomain: 'citypass-seed.com',
    },

    // DANCE
    {
      sourceUrl: 'https://citypass-seed.com/sf/ballet-swan-lake',
      title: 'SF Ballet: Swan Lake',
      subtitle: 'Classical Ballet Performance',
      description: 'San Francisco Ballet performs Tchaikovsky\'s timeless masterpiece. Breathtaking choreography and world-class dancers bring this classic to life.',
      category: 'DANCE',
      organizer: 'SF Ballet',
      venueName: 'War Memorial Opera House',
      address: '301 Van Ness Ave, San Francisco, CA 94102',
      neighborhood: 'Civic Center',
      city: 'San Francisco',
      lat: 37.7788,
      lon: -122.4210,
      startTime: getDaysFromNow(11, 19, 30),
      endTime: getDaysFromNow(11, 22, 0),
      timezone: 'America/Los_Angeles',
      priceMin: 60,
      priceMax: 180,
      currency: 'USD',
      tags: ['ballet', 'classical', 'dance', 'swan-lake'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/swan-lake',
      accessibility: ['wheelchair-accessible', 'formal-attire'],
      sourceDomain: 'citypass-seed.com',
    },

    // NETWORKING
    {
      sourceUrl: 'https://citypass-seed.com/sf/startup-mixer',
      title: 'Silicon Valley Startup Networking',
      subtitle: 'Connect with Tech Founders',
      description: 'Monthly mixer for startup founders, engineers, and investors. Featuring lightning pitches and open networking. Free appetizers and drinks.',
      category: 'NETWORKING',
      organizer: 'SF Tech Hub',
      venueName: 'Galvanize SF',
      address: '44 Tehama St, San Francisco, CA 94105',
      neighborhood: 'SoMa',
      city: 'San Francisco',
      lat: 37.7872,
      lon: -122.3989,
      startTime: getDaysFromNow(4, 18, 0),
      endTime: getDaysFromNow(4, 21, 0),
      timezone: 'America/Los_Angeles',
      priceMin: 0,
      priceMax: 0,
      currency: 'USD',
      tags: ['networking', 'startup', 'tech', 'free', 'business'],
      imageUrl: null,
      bookingUrl: null,
      accessibility: ['free', 'professional', 'wheelchair-accessible'],
      sourceDomain: 'citypass-seed.com',
    },

    // FAMILY
    {
      sourceUrl: 'https://citypass-seed.com/sf/exploratorium-kids',
      title: 'Family Day at Exploratorium',
      subtitle: 'Interactive Science Museum',
      description: 'Hands-on science exhibits perfect for kids and adults. Special family programming includes live demonstrations and interactive workshops.',
      category: 'FAMILY',
      organizer: 'Exploratorium',
      venueName: 'Exploratorium',
      address: 'Pier 15, San Francisco, CA 94111',
      neighborhood: 'Embarcadero',
      city: 'San Francisco',
      lat: 37.8016,
      lon: -122.3978,
      startTime: getDaysFromNow(6, 10, 0),
      endTime: getDaysFromNow(6, 17, 0),
      timezone: 'America/Los_Angeles',
      priceMin: 30,
      priceMax: 30,
      currency: 'USD',
      tags: ['family', 'science', 'museum', 'interactive', 'educational'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/exploratorium',
      accessibility: ['family-friendly', 'wheelchair-accessible'],
      sourceDomain: 'citypass-seed.com',
    },

    // OTHER
    {
      sourceUrl: 'https://citypass-seed.com/sf/trivia-dolores',
      title: 'Trivia Night at Dolores Park Cafe',
      subtitle: 'Weekly Quiz Competition',
      description: 'Test your knowledge at this popular weekly trivia night. Themed rounds, prizes for winners, and a fun community atmosphere. Free to play!',
      category: 'OTHER',
      organizer: 'Dolores Park Cafe',
      venueName: 'Dolores Park Cafe',
      address: '501 Dolores St, San Francisco, CA 94110',
      neighborhood: 'Mission',
      city: 'San Francisco',
      lat: 37.7613,
      lon: -122.4264,
      startTime: getDaysFromNow(2, 19, 30),
      endTime: getDaysFromNow(2, 22, 0),
      timezone: 'America/Los_Angeles',
      priceMin: 0,
      priceMax: 0,
      currency: 'USD',
      tags: ['trivia', 'social', 'free', 'community'],
      imageUrl: null,
      bookingUrl: null,
      accessibility: ['free', 'casual', 'team-activity'],
      sourceDomain: 'citypass-seed.com',
    },
  ],

  // Continue with Los Angeles, Chicago, and Boston with similar comprehensive events...
  'Los Angeles': [
    // MUSIC
    {
      sourceUrl: 'https://citypass-seed.com/la/hollywood-bowl',
      title: 'LA Philharmonic at Hollywood Bowl',
      subtitle: 'Summer Concert Series',
      description: 'Experience the magic of live orchestra under the stars at the iconic Hollywood Bowl. Tonight features film scores and classical masterworks.',
      category: 'MUSIC',
      organizer: 'LA Phil',
      venueName: 'Hollywood Bowl',
      address: '2301 N Highland Ave, Los Angeles, CA 90068',
      neighborhood: 'Hollywood Hills',
      city: 'Los Angeles',
      lat: 34.1128,
      lon: -118.3393,
      startTime: getDaysFromNow(5, 19, 30),
      endTime: getDaysFromNow(5, 22, 0),
      timezone: 'America/Los_Angeles',
      priceMin: 40,
      priceMax: 150,
      currency: 'USD',
      tags: ['classical', 'orchestra', 'outdoor', 'iconic-venue'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/hollywood-bowl',
      accessibility: ['wheelchair-accessible', 'outdoor'],
      sourceDomain: 'citypass-seed.com',
    },
    {
      sourceUrl: 'https://citypass-seed.com/la/troubadour-indie',
      title: 'Indie Rock Night at The Troubadour',
      subtitle: 'Legendary West Hollywood Venue',
      description: 'See tomorrow\'s headliners today at the historic Troubadour. This intimate venue has launched countless careers. Tonight: three up-and-coming bands.',
      category: 'MUSIC',
      organizer: 'Troubadour',
      venueName: 'The Troubadour',
      address: '9081 Santa Monica Blvd, West Hollywood, CA 90069',
      neighborhood: 'West Hollywood',
      city: 'Los Angeles',
      lat: 34.0898,
      lon: -118.3879,
      startTime: getDaysFromNow(3, 20, 0),
      endTime: getDaysFromNow(3, 23, 0),
      timezone: 'America/Los_Angeles',
      priceMin: 20,
      priceMax: 30,
      currency: 'USD',
      minAge: 21,
      tags: ['indie', 'rock', 'live-music', 'historic-venue'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/troubadour',
      accessibility: ['21+', 'standing-room'],
      sourceDomain: 'citypass-seed.com',
    },

    // COMEDY
    {
      sourceUrl: 'https://citypass-seed.com/la/comedy-store',
      title: 'Comedy Night at The Comedy Store',
      subtitle: 'Stand-Up Comedy Showcase',
      description: 'Catch rising stars and comedy legends on the Sunset Strip. This legendary club has hosted everyone from Robin Williams to Dave Chappelle.',
      category: 'COMEDY',
      organizer: 'The Comedy Store',
      venueName: 'The Comedy Store',
      address: '8433 Sunset Blvd, West Hollywood, CA 90069',
      neighborhood: 'West Hollywood',
      city: 'Los Angeles',
      lat: 40.7979,
      lon: -118.3767,
      startTime: getDaysFromNow(2, 20, 0),
      endTime: getDaysFromNow(2, 22, 30),
      timezone: 'America/Los_Angeles',
      priceMin: 25,
      priceMax: 40,
      currency: 'USD',
      minAge: 21,
      tags: ['comedy', 'stand-up', 'nightlife', 'sunset-strip'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/comedy-store',
      accessibility: ['21+', 'wheelchair-accessible'],
      sourceDomain: 'citypass-seed.com',
    },

    // FITNESS
    {
      sourceUrl: 'https://citypass-seed.com/la/venice-beach-yoga',
      title: 'Sunrise Yoga at Venice Beach',
      subtitle: 'Free Community Yoga',
      description: 'Start your day with yoga on the beach with stunning ocean views. All levels welcome, bring your own mat. A perfect way to greet the California sunrise.',
      category: 'FITNESS',
      organizer: 'Venice Beach Yoga',
      venueName: 'Venice Beach',
      address: 'Venice Beach Boardwalk, Venice, CA 90291',
      neighborhood: 'Venice',
      city: 'Los Angeles',
      lat: 33.985,
      lon: -118.4695,
      startTime: getDaysFromNow(4, 6, 30),
      endTime: getDaysFromNow(4, 7, 30),
      timezone: 'America/Los_Angeles',
      priceMin: 0,
      priceMax: 0,
      currency: 'USD',
      tags: ['yoga', 'fitness', 'free', 'outdoor', 'beach'],
      imageUrl: null,
      bookingUrl: null,
      accessibility: ['outdoor', 'free', 'all-levels'],
      sourceDomain: 'citypass-seed.com',
    },
    {
      sourceUrl: 'https://citypass-seed.com/la/runyon-canyon-hike',
      title: 'Group Hike at Runyon Canyon',
      subtitle: 'Fitness & Networking',
      description: 'Join fellow fitness enthusiasts for a morning hike with incredible city and ocean views. Great workout plus networking opportunity. Dog-friendly!',
      category: 'FITNESS',
      organizer: 'LA Hiking Club',
      venueName: 'Runyon Canyon Park',
      address: '2000 N Fuller Ave, Los Angeles, CA 90046',
      neighborhood: 'Hollywood Hills',
      city: 'Los Angeles',
      lat: 34.1105,
      lon: -118.3516,
      startTime: getDaysFromNow(6, 8, 0),
      endTime: getDaysFromNow(6, 10, 0),
      timezone: 'America/Los_Angeles',
      priceMin: 0,
      priceMax: 0,
      currency: 'USD',
      tags: ['hiking', 'fitness', 'outdoor', 'free', 'dog-friendly'],
      imageUrl: null,
      bookingUrl: null,
      accessibility: ['free', 'outdoor', 'dog-friendly'],
      sourceDomain: 'citypass-seed.com',
    },

    // Continue with more LA events for FOOD, ARTS, THEATRE, DANCE, NETWORKING, FAMILY, OTHER...
  ],

  'Chicago': [
    // MUSIC
    {
      sourceUrl: 'https://citypass-seed.com/chi/blues-festival',
      title: 'Chicago Blues Festival',
      subtitle: 'Free Blues Music Festival',
      description: 'Three days of authentic Chicago blues in Millennium Park. Featuring legendary blues artists and rising stars keeping the tradition alive.',
      category: 'MUSIC',
      organizer: 'City of Chicago',
      venueName: 'Millennium Park',
      address: '201 E Randolph St, Chicago, IL 60602',
      neighborhood: 'The Loop',
      city: 'Chicago',
      lat: 41.8826,
      lon: -87.6226,
      startTime: getDaysFromNow(7, 16, 0),
      endTime: getDaysFromNow(7, 21, 0),
      timezone: 'America/Chicago',
      priceMin: 0,
      priceMax: 0,
      currency: 'USD',
      tags: ['music', 'blues', 'festival', 'outdoor', 'free'],
      imageUrl: null,
      bookingUrl: null,
      accessibility: ['outdoor', 'free', 'wheelchair-accessible'],
      sourceDomain: 'citypass-seed.com',
    },
    {
      sourceUrl: 'https://citypass-seed.com/chi/jazz-showcase',
      title: 'Jazz Night at Jazz Showcase',
      subtitle: 'Chicago\'s Premier Jazz Club',
      description: 'Experience world-class jazz in an intimate setting. Tonight features a legendary jazz trio performing bebop and modern jazz standards.',
      category: 'MUSIC',
      organizer: 'Jazz Showcase',
      venueName: 'Jazz Showcase',
      address: '806 S Plymouth Ct, Chicago, IL 60605',
      neighborhood: 'South Loop',
      city: 'Chicago',
      lat: 41.8718,
      lon: -87.6308,
      startTime: getDaysFromNow(4, 20, 0),
      endTime: getDaysFromNow(4, 22, 30),
      timezone: 'America/Chicago',
      priceMin: 30,
      priceMax: 50,
      currency: 'USD',
      minAge: 21,
      tags: ['jazz', 'music', 'live', 'intimate'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/jazz-showcase',
      accessibility: ['21+', 'wheelchair-accessible'],
      sourceDomain: 'citypass-seed.com',
    },

    // FOOD
    {
      sourceUrl: 'https://citypass-seed.com/chi/deep-dish-class',
      title: 'Deep Dish Pizza Making Class',
      subtitle: 'Learn to Make Chicago-Style Pizza',
      description: 'Hands-on class teaching authentic Chicago deep dish techniques from a third-generation pizza maker. Eat what you make and take home the recipe!',
      category: 'FOOD',
      organizer: 'Chicago Culinary School',
      venueName: 'Chicago Culinary School',
      address: '225 W Hubbard St, Chicago, IL 60654',
      neighborhood: 'River North',
      city: 'Chicago',
      lat: 41.8899,
      lon: -87.6363,
      startTime: getDaysFromNow(5, 18, 0),
      endTime: getDaysFromNow(5, 20, 30),
      timezone: 'America/Chicago',
      priceMin: 85,
      priceMax: 85,
      currency: 'USD',
      tags: ['food', 'cooking', 'pizza', 'class', 'hands-on'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/deep-dish',
      accessibility: ['indoor', 'hands-on'],
      sourceDomain: 'citypass-seed.com',
    },

    // Continue with more Chicago events...
  ],

  'Boston': [
    // MUSIC
    {
      sourceUrl: 'https://citypass-seed.com/bos/symphony-hall',
      title: 'Boston Symphony Orchestra at Symphony Hall',
      subtitle: 'Beethoven Symphony No. 9',
      description: 'Experience Beethoven\'s masterpiece performed by one of the world\'s great orchestras in a hall renowned for its perfect acoustics.',
      category: 'MUSIC',
      organizer: 'Boston Symphony Orchestra',
      venueName: 'Symphony Hall',
      address: '301 Massachusetts Ave, Boston, MA 02115',
      neighborhood: 'Back Bay',
      city: 'Boston',
      lat: 42.3427,
      lon: -71.0851,
      startTime: getDaysFromNow(8, 19, 30),
      endTime: getDaysFromNow(8, 22, 0),
      timezone: 'America/New_York',
      priceMin: 55,
      priceMax: 150,
      currency: 'USD',
      tags: ['classical', 'orchestra', 'symphony', 'beethoven'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/bso',
      accessibility: ['wheelchair-accessible'],
      sourceDomain: 'citypass-seed.com',
    },

    // FITNESS
    {
      sourceUrl: 'https://citypass-seed.com/bos/harbor-run',
      title: 'Boston Harbor 5K Run',
      subtitle: 'Waterfront Running Event',
      description: 'Scenic 5K along the Boston Harbor with city skyline views. Benefits local youth running programs. All paces welcome, post-race refreshments included.',
      category: 'FITNESS',
      organizer: 'Boston Running Club',
      venueName: 'Boston Harborwalk',
      address: 'Fan Pier, Boston, MA 02210',
      neighborhood: 'Seaport',
      city: 'Boston',
      lat: 42.3539,
      lon: -71.0443,
      startTime: getDaysFromNow(6, 8, 0),
      endTime: getDaysFromNow(6, 10, 0),
      timezone: 'America/New_York',
      priceMin: 30,
      priceMax: 30,
      currency: 'USD',
      tags: ['running', '5k', 'fitness', 'outdoor', 'harbor'],
      imageUrl: null,
      bookingUrl: 'https://citypass-seed.com/tickets/harbor-5k',
      accessibility: ['outdoor', 'all-paces'],
      sourceDomain: 'citypass-seed.com',
    },

    // Continue with more Boston events...
  ],
};

export const DEFAULT_SEED_CITIES = Object.keys(SEED_EVENTS_BY_CITY);
