// Quick script to seed the database directly
const { PrismaClient } = require('@prisma/client');
const crypto = require('crypto');

const prisma = new PrismaClient({
  datasourceUrl: 'postgresql://postgres:JfWnsUut6f7XSEMA@eoabuyvlsakqkuqtkwxo.db.us-west-2.nhost.run:5432/eoabuyvlsakqkuqtkwxo'
});

function canonicalUrlHash(url) {
  return crypto.createHash('sha256').update(url.toLowerCase().trim()).digest('hex');
}

function contentChecksum(data) {
  const normalized = JSON.stringify(data, Object.keys(data).sort());
  return crypto.createHash('md5').update(normalized).digest('hex');
}

const EVENTS = [
  {
    sourceUrl: 'https://test.com/comedy-night',
    title: 'Comedy Night at Comedy Cellar',
    subtitle: 'Live Stand-Up Comedy',
    description: 'An unforgettable night of laughter with top NYC comedians',
    category: 'COMEDY',
    organizer: 'Comedy Cellar',
    venueName: 'Comedy Cellar',
    address: '117 MacDougal St, New York, NY 10012',
    neighborhood: 'Greenwich Village',
    city: 'New York',
    lat: 40.7298,
    lon: -74.001,
    startTime: '2025-12-08T21:00:00-05:00',
    endTime: '2025-12-08T23:30:00-05:00',
    timezone: 'America/New_York',
    priceMin: 20,
    priceMax: 30,
    currency: 'USD',
    tags: ['comedy', 'stand-up', 'entertainment'],
    bookingUrl: 'https://test.com/comedy-tickets',
    accessibility: ['wheelchair-accessible'],
    sourceDomain: 'test.com',
  },
  {
    sourceUrl: 'https://test.com/brooklyn-brewery-tour',
    title: 'Brooklyn Brewery Tour',
    subtitle: 'Craft Beer Tasting',
    description: 'Tour the brewery and sample Brooklyn\'s finest craft beers',
    category: 'FOOD',
    organizer: 'Brooklyn Brewery',
    venueName: 'Brooklyn Brewery',
    address: '79 N 11th St, Brooklyn, NY 11249',
    neighborhood: 'Williamsburg',
    city: 'New York',
    lat: 40.7218,
    lon: -73.9585,
    startTime: '2025-11-20T15:00:00-05:00',
    endTime: '2025-11-20T17:00:00-05:00',
    timezone: 'America/New_York',
    priceMin: 15,
    priceMax: 15,
    currency: 'USD',
    minAge: 21,
    tags: ['brewery', 'beer', 'tour'],
    bookingUrl: 'https://test.com/brewery-tickets',
    accessibility: ['21+'],
    sourceDomain: 'test.com',
  },
  {
    sourceUrl: 'https://test.com/central-park-yoga',
    title: 'Sunrise Yoga in Central Park',
    subtitle: 'Free Outdoor Yoga Session',
    description: 'Start your day with a peaceful yoga class in Central Park',
    category: 'FITNESS',
    organizer: 'NYC Parks',
    venueName: 'Central Park Great Lawn',
    address: 'Central Park, New York, NY 10024',
    neighborhood: 'Upper West Side',
    city: 'New York',
    lat: 40.7794,
    lon: -73.9632,
    startTime: '2025-11-25T07:00:00-05:00',
    endTime: '2025-11-25T08:00:00-05:00',
    timezone: 'America/New_York',
    priceMin: 0,
    priceMax: 0,
    currency: 'USD',
    tags: ['yoga', 'fitness', 'free', 'outdoor'],
    accessibility: ['outdoor', 'free'],
    sourceDomain: 'test.com',
  },
  {
    sourceUrl: 'https://test.com/met-museum-night',
    title: 'The Met After Hours',
    subtitle: 'Evening Museum Tour',
    description: 'Explore The Metropolitan Museum of Art with fewer crowds',
    category: 'ARTS',
    organizer: 'The Met',
    venueName: 'The Metropolitan Museum of Art',
    address: '1000 5th Ave, New York, NY 10028',
    neighborhood: 'Upper East Side',
    city: 'New York',
    lat: 40.7794,
    lon: -73.9632,
    startTime: '2025-11-26T18:00:00-05:00',
    endTime: '2025-11-26T21:00:00-05:00',
    timezone: 'America/New_York',
    priceMin: 30,
    priceMax: 30,
    currency: 'USD',
    tags: ['museum', 'art', 'culture'],
    bookingUrl: 'https://test.com/met-tickets',
    accessibility: ['wheelchair-accessible'],
    sourceDomain: 'test.com',
  },
  {
    sourceUrl: 'https://test.com/jazz-at-lincoln-center',
    title: 'Jazz at Lincoln Center',
    subtitle: 'Live Jazz Performance',
    description: 'World-class jazz in the heart of Manhattan',
    category: 'MUSIC',
    organizer: 'Jazz at Lincoln Center',
    venueName: 'Dizzy\'s Club',
    address: '10 Columbus Circle, New York, NY 10019',
    neighborhood: 'Midtown',
    city: 'New York',
    lat: 40.7681,
    lon: -73.9819,
    startTime: '2025-11-27T20:00:00-05:00',
    endTime: '2025-11-27T22:30:00-05:00',
    timezone: 'America/New_York',
    priceMin: 35,
    priceMax: 65,
    currency: 'USD',
    minAge: 21,
    tags: ['jazz', 'music', 'live'],
    bookingUrl: 'https://test.com/jazz-tickets',
    accessibility: ['21+', 'wheelchair-accessible'],
    sourceDomain: 'test.com',
  },
  {
    sourceUrl: 'https://test.com/brooklyn-flea',
    title: 'Brooklyn Flea Market',
    subtitle: 'Vintage Shopping & Food',
    description: 'Browse vintage finds and enjoy local food vendors',
    category: 'OTHER',
    organizer: 'Brooklyn Flea',
    venueName: 'Brooklyn Flea Dumbo',
    address: 'Manhattan Bridge Archway, Brooklyn, NY 11201',
    neighborhood: 'DUMBO',
    city: 'New York',
    lat: 40.7033,
    lon: -73.9875,
    startTime: '2025-11-23T10:00:00-05:00',
    endTime: '2025-11-23T17:00:00-05:00',
    timezone: 'America/New_York',
    priceMin: 0,
    priceMax: 0,
    currency: 'USD',
    tags: ['market', 'vintage', 'shopping', 'free'],
    accessibility: ['outdoor', 'free'],
    sourceDomain: 'test.com',
  },
  {
    sourceUrl: 'https://test.com/broadway-show',
    title: 'Hamilton on Broadway',
    subtitle: 'Award-Winning Musical',
    description: 'Experience the revolutionary story of Alexander Hamilton',
    category: 'THEATRE',
    organizer: 'Broadway',
    venueName: 'Richard Rodgers Theatre',
    address: '226 W 46th St, New York, NY 10036',
    neighborhood: 'Theater District',
    city: 'New York',
    lat: 40.7590,
    lon: -73.9845,
    startTime: '2025-11-28T20:00:00-05:00',
    endTime: '2025-11-28T22:45:00-05:00',
    timezone: 'America/New_York',
    priceMin: 79,
    priceMax: 299,
    currency: 'USD',
    tags: ['theater', 'musical', 'broadway'],
    bookingUrl: 'https://test.com/hamilton-tickets',
    accessibility: ['wheelchair-accessible'],
    sourceDomain: 'test.com',
  },
  {
    sourceUrl: 'https://test.com/queens-night-market',
    title: 'Queens Night Market',
    subtitle: 'International Street Food',
    description: 'Sample dishes from over 80 countries at this outdoor night market',
    category: 'FOOD',
    organizer: 'Queens Night Market',
    venueName: 'Flushing Meadows Corona Park',
    address: 'Corona, NY 11368',
    neighborhood: 'Flushing',
    city: 'New York',
    lat: 40.7498,
    lon: -73.8456,
    startTime: '2025-11-22T18:00:00-05:00',
    endTime: '2025-11-22T23:00:00-05:00',
    timezone: 'America/New_York',
    priceMin: 0,
    priceMax: 0,
    currency: 'USD',
    tags: ['food', 'market', 'international', 'free'],
    accessibility: ['outdoor', 'free'],
    sourceDomain: 'test.com',
  },
  {
    sourceUrl: 'https://test.com/chelsea-art-galleries',
    title: 'Chelsea Gallery Crawl',
    subtitle: 'Contemporary Art Tour',
    description: 'Explore dozens of contemporary art galleries in Chelsea',
    category: 'ARTS',
    organizer: 'Chelsea Art Galleries',
    venueName: 'Chelsea Arts District',
    address: 'W 24th St, New York, NY 10011',
    neighborhood: 'Chelsea',
    city: 'New York',
    lat: 40.7465,
    lon: -74.0034,
    startTime: '2025-11-24T14:00:00-05:00',
    endTime: '2025-11-24T18:00:00-05:00',
    timezone: 'America/New_York',
    priceMin: 0,
    priceMax: 0,
    currency: 'USD',
    tags: ['art', 'galleries', 'culture', 'free'],
    accessibility: ['free'],
    sourceDomain: 'test.com',
  },
  {
    sourceUrl: 'https://test.com/rockaway-surf',
    title: 'Surf Lesson at Rockaway Beach',
    subtitle: 'Beginner Surfing Class',
    description: 'Learn to surf with experienced instructors at NYC\'s best beach',
    category: 'FITNESS',
    organizer: 'Rockaway Surf School',
    venueName: 'Rockaway Beach',
    address: 'Beach 87th St, Queens, NY 11693',
    neighborhood: 'Rockaway',
    city: 'New York',
    lat: 40.5850,
    lon: -73.8166,
    startTime: '2025-11-21T10:00:00-05:00',
    endTime: '2025-11-21T12:00:00-05:00',
    timezone: 'America/New_York',
    priceMin: 65,
    priceMax: 65,
    currency: 'USD',
    tags: ['surfing', 'beach', 'fitness', 'outdoor'],
    bookingUrl: 'https://test.com/surf-lesson',
    accessibility: ['outdoor'],
    sourceDomain: 'test.com',
  },
  {
    sourceUrl: 'https://test.com/smorgasburg',
    title: 'Smorgasburg Brooklyn',
    subtitle: 'Open-Air Food Market',
    description: 'America\'s largest weekly open-air food market',
    category: 'FOOD',
    organizer: 'Smorgasburg',
    venueName: 'East River State Park',
    address: '90 Kent Ave, Brooklyn, NY 11249',
    neighborhood: 'Williamsburg',
    city: 'New York',
    lat: 40.7218,
    lon: -73.9626,
    startTime: '2025-11-23T11:00:00-05:00',
    endTime: '2025-11-23T18:00:00-05:00',
    timezone: 'America/New_York',
    priceMin: 0,
    priceMax: 0,
    currency: 'USD',
    tags: ['food', 'market', 'outdoor', 'free'],
    accessibility: ['outdoor', 'free'],
    sourceDomain: 'test.com',
  },
  {
    sourceUrl: 'https://test.com/rooftop-cinema',
    title: 'Rooftop Cinema Club',
    subtitle: 'Outdoor Movie Screening',
    description: 'Watch classic films under the stars with Manhattan skyline views',
    category: 'OTHER',
    organizer: 'Rooftop Cinema Club',
    venueName: 'Industry City Rooftop',
    address: '220 36th St, Brooklyn, NY 11232',
    neighborhood: 'Sunset Park',
    city: 'New York',
    lat: 40.6563,
    lon: -74.0093,
    startTime: '2025-11-29T19:30:00-05:00',
    endTime: '2025-11-29T22:00:00-05:00',
    timezone: 'America/New_York',
    priceMin: 18,
    priceMax: 25,
    currency: 'USD',
    tags: ['movies', 'outdoor', 'rooftop'],
    bookingUrl: 'https://test.com/rooftop-tickets',
    accessibility: ['outdoor'],
    sourceDomain: 'test.com',
  },
];

async function seed() {
  console.log('🌱 Starting database seeding...');

  let created = 0;

  for (const event of EVENTS) {
    const startTime = new Date(event.startTime);
    const endTime = event.endTime ? new Date(event.endTime) : null;
    const urlHash = canonicalUrlHash(event.sourceUrl);

    // Check if already exists
    const existing = await prisma.event.findFirst({
      where: {
        canonicalUrlHash: urlHash,
        startTime,
      },
    });

    if (existing) {
      console.log(`⏭️  Skipping: ${event.title} (already exists)`);
      continue;
    }

    const checksum = contentChecksum({
      title: event.title,
      description: event.description,
      start_time: startTime.toISOString(),
      venue_name: event.venueName,
      price_min: event.priceMin,
      price_max: event.priceMax,
    });

    await prisma.event.create({
      data: {
        sourceUrl: event.sourceUrl,
        title: event.title,
        subtitle: event.subtitle,
        description: event.description,
        category: event.category,
        organizer: event.organizer,
        venueName: event.venueName,
        address: event.address,
        neighborhood: event.neighborhood,
        city: event.city,
        lat: event.lat,
        lon: event.lon,
        startTime,
        endTime,
        timezone: event.timezone,
        priceMin: event.priceMin,
        priceMax: event.priceMax,
        currency: event.currency,
        minAge: event.minAge || null,
        tags: event.tags || [],
        imageUrl: null,
        bookingUrl: event.bookingUrl || null,
        accessibility: event.accessibility || [],
        sourceDomain: event.sourceDomain,
        canonicalUrlHash: urlHash,
        checksum,
      },
    });

    console.log(`✅ Created: ${event.title}`);
    created++;
  }

  console.log(`\n🎉 Seeding complete! Created ${created} events.`);
}

seed()
  .catch((e) => {
    console.error('❌ Seeding failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
