import { PrismaClient, EventCategory } from '@prisma/client';
const prisma = new PrismaClient();
async function main() {
    console.log('🌱 Creating comprehensive event database...\n');
    const now = new Date();
    const daysFromNow = (days, hour = 20) => {
        const date = new Date(now);
        date.setDate(date.getDate() + days);
        date.setHours(hour, 0, 0, 0);
        return date;
    };
    const comprehensiveEvents = [
        {
            sourceUrl: 'https://www.boweryballroom.com/event/japanese-breakfast-2025',
            title: 'Japanese Breakfast - Jubilee Tour',
            city: 'New York',
            startTime: daysFromNow(5, 19),
            category: EventCategory.MUSIC,
            venueName: 'The Bowery Ballroom',
            neighborhood: 'Lower East Side',
            priceMin: 35.0,
            priceMax: 45.0,
            description: 'Indie pop sensation Japanese Breakfast returns with an intimate performance of hits from Jubilee and Soft Sounds.',
            sourceDomain: 'boweryballroom.com',
            checksum: 'jb_2025_bowery',
            canonicalUrlHash: 'hash_jb_bowery',
            imageUrl: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800',
            ticketUrl: 'https://www.boweryballroom.com/tickets',
        },
        {
            sourceUrl: 'https://www.brooklynbowl.com/events/lettuce-funk-jam',
            title: 'Lettuce - NYC Funk Jam Session',
            city: 'New York',
            startTime: daysFromNow(8, 21),
            category: EventCategory.MUSIC,
            venueName: 'Brooklyn Bowl',
            neighborhood: 'Williamsburg',
            priceMin: 30.0,
            priceMax: 40.0,
            description: 'Legendary funk band Lettuce brings their improvisational magic to Brooklyn Bowl. Get ready to groove!',
            sourceDomain: 'brooklynbowl.com',
            checksum: 'lettuce_bbowl',
            canonicalUrlHash: 'hash_lettuce',
            imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800',
            ticketUrl: 'https://www.brooklynbowl.com/tickets',
        },
        {
            sourceUrl: 'https://www.brooklynmirage.com/khruangbin',
            title: 'Khruangbin - Mordechai Tour',
            city: 'New York',
            startTime: daysFromNow(12, 20),
            category: EventCategory.MUSIC,
            venueName: 'The Brooklyn Mirage',
            neighborhood: 'East Williamsburg',
            priceMin: 55.0,
            priceMax: 75.0,
            description: 'Thai-funk trio Khruangbin performs under the stars at Brooklyn\'s premier outdoor venue.',
            sourceDomain: 'brooklynmirage.com',
            checksum: 'khruangbin_mirage',
            canonicalUrlHash: 'hash_khruangbin',
            imageUrl: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800',
        },
        {
            sourceUrl: 'https://www.saintvitusbar.com/metal-monday',
            title: 'Metal Monday - Doom & Sludge Night',
            city: 'New York',
            startTime: daysFromNow(2, 22),
            category: EventCategory.MUSIC,
            venueName: 'Saint Vitus Bar',
            neighborhood: 'Greenpoint',
            priceMin: 15.0,
            priceMax: 20.0,
            description: 'Weekly metal showcase featuring local doom and sludge bands. BYOB friendly.',
            sourceDomain: 'saintvitusbar.com',
            checksum: 'metal_monday',
            canonicalUrlHash: 'hash_metal_mon',
            imageUrl: 'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=800',
        },
        {
            sourceUrl: 'https://www.jazz-standard.com/mingus-big-band',
            title: 'Mingus Big Band - Monday Night Residency',
            city: 'New York',
            startTime: daysFromNow(4, 19),
            category: EventCategory.MUSIC,
            venueName: 'Blue Note Jazz Club',
            neighborhood: 'Greenwich Village',
            priceMin: 45.0,
            priceMax: 65.0,
            description: 'The legendary Mingus Big Band continues their decades-long Monday residency with cutting-edge jazz.',
            sourceDomain: 'bluenotejazz.com',
            checksum: 'mingus_bluenote',
            canonicalUrlHash: 'hash_mingus',
            imageUrl: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800',
        },
        {
            sourceUrl: 'https://www.roughtradebrooklyn.com/dj-night',
            title: 'Rough Trade DJ Night - Vinyl Only',
            city: 'New York',
            startTime: daysFromNow(6, 22),
            category: EventCategory.MUSIC,
            venueName: 'Rough Trade NYC',
            neighborhood: 'Williamsburg',
            priceMin: 10.0,
            priceMax: 15.0,
            description: 'Local DJs spin rare vinyl all night. Free beer with ticket purchase before 11pm.',
            sourceDomain: 'roughtradebrooklyn.com',
            checksum: 'rt_vinyl',
            canonicalUrlHash: 'hash_rt_vinyl',
            imageUrl: 'https://images.unsplash.com/photo-1571330735066-03aaa9429d89?w=800',
        },
        {
            sourceUrl: 'https://www.comedycellar.com/shows/hannibal-buress',
            title: 'Hannibal Buress - Surprise Drop-In',
            city: 'New York',
            startTime: daysFromNow(3, 20),
            category: EventCategory.COMEDY,
            venueName: 'Comedy Cellar',
            neighborhood: 'Greenwich Village',
            priceMin: 25.0,
            priceMax: 35.0,
            description: 'Comedy legend Hannibal Buress testing new material. Lineup subject to change.',
            sourceDomain: 'comedycellar.com',
            checksum: 'hannibal_cellar',
            canonicalUrlHash: 'hash_hannibal',
            imageUrl: 'https://images.unsplash.com/photo-1527224857830-43a7acc85260?w=800',
        },
        {
            sourceUrl: 'https://ucbtheatre.com/improv-4-humans',
            title: 'Improv 4 Humans with Matt Besser',
            city: 'New York',
            startTime: daysFromNow(7, 21),
            category: EventCategory.COMEDY,
            venueName: 'UCB Theatre',
            neighborhood: 'Hell\'s Kitchen',
            priceMin: 12.0,
            priceMax: 15.0,
            description: 'UCB co-founder Matt Besser hosts this long-running improv podcast live show.',
            sourceDomain: 'ucbtheatre.com',
            checksum: 'improv_4_humans',
            canonicalUrlHash: 'hash_i4h',
            imageUrl: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=800',
        },
        {
            sourceUrl: 'https://www.standupny.com/weekend-showcase',
            title: 'Weekend Comedy Showcase',
            city: 'New York',
            startTime: daysFromNow(10, 22),
            category: EventCategory.COMEDY,
            venueName: 'Stand Up NY',
            neighborhood: 'Upper West Side',
            priceMin: 20.0,
            priceMax: 30.0,
            description: '5 comedians, 2 hours of laughs. Features comics from Comedy Central and Netflix.',
            sourceDomain: 'standupny.com',
            checksum: 'standup_weekend',
            canonicalUrlHash: 'hash_standup_we',
            imageUrl: 'https://images.unsplash.com/photo-1613009664984-e900c4bf34cb?w=800',
        },
        {
            sourceUrl: 'https://www.smorgasburg.com/williamsburg',
            title: 'Smorgasburg - Brooklyn Flea Food Market',
            city: 'New York',
            startTime: daysFromNow(2, 11),
            category: EventCategory.FOOD,
            venueName: 'East River State Park',
            neighborhood: 'Williamsburg',
            priceMin: 0.0,
            priceMax: 0.0,
            description: 'America\'s largest weekly open-air food market. 100+ vendors, free admission.',
            sourceDomain: 'smorgasburg.com',
            checksum: 'smorg_wburg',
            canonicalUrlHash: 'hash_smorg',
            imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
        },
        {
            sourceUrl: 'https://www.timessquarebrewery.com/beer-tasting',
            title: 'Craft Beer Tasting Flight Night',
            city: 'New York',
            startTime: daysFromNow(5, 18),
            category: EventCategory.FOOD,
            venueName: 'Other Half Brewing',
            neighborhood: 'Gowanus',
            priceMin: 25.0,
            priceMax: 40.0,
            description: 'Guided tasting of 6 limited-release IPAs with the head brewer. Includes pairing snacks.',
            sourceDomain: 'otherhalfbrewing.com',
            checksum: 'otherhalf_tasting',
            canonicalUrlHash: 'hash_otherhalf',
            imageUrl: 'https://images.unsplash.com/photo-1532634896-c840ed60e980?w=800',
        },
        {
            sourceUrl: 'https://www.chelsea-market.com/wine-walk',
            title: 'Chelsea Market Wine Walk',
            city: 'New York',
            startTime: daysFromNow(14, 17),
            category: EventCategory.FOOD,
            venueName: 'Chelsea Market',
            neighborhood: 'Chelsea',
            priceMin: 45.0,
            priceMax: 55.0,
            description: 'Explore 8 wine tastings paired with artisan foods throughout Chelsea Market.',
            sourceDomain: 'chelseamarket.com',
            checksum: 'chelsea_wine',
            canonicalUrlHash: 'hash_chelsea_wine',
            imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800',
        },
        {
            sourceUrl: 'https://www.moma.org/visit/late-night',
            title: 'MoMA Late Night: Immersive Art Experience',
            city: 'New York',
            startTime: daysFromNow(9, 20),
            category: EventCategory.ARTS,
            venueName: 'Museum of Modern Art',
            neighborhood: 'Midtown',
            priceMin: 15.0,
            priceMax: 25.0,
            description: 'Museums open until midnight with live DJs, cocktails, and special exhibitions.',
            sourceDomain: 'moma.org',
            checksum: 'moma_late',
            canonicalUrlHash: 'hash_moma_late',
            imageUrl: 'https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=800',
        },
        {
            sourceUrl: 'https://www.theshed.org/program/multimedia-installation',
            title: 'teamLab: Digital Art Borderless NYC',
            city: 'New York',
            startTime: daysFromNow(15, 10),
            category: EventCategory.ARTS,
            venueName: 'The Shed',
            neighborhood: 'Hudson Yards',
            priceMin: 40.0,
            priceMax: 60.0,
            description: 'Immersive digital art installation with 50+ interactive exhibits. Timed entry.',
            sourceDomain: 'theshed.org',
            checksum: 'teamlab_shed',
            canonicalUrlHash: 'hash_teamlab',
            imageUrl: 'https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800',
        },
        {
            sourceUrl: 'https://www.metmuseum.org/events/gallery-talks',
            title: 'Met Museum Gallery Talk: Egyptian Art',
            city: 'New York',
            startTime: daysFromNow(11, 14),
            category: EventCategory.ARTS,
            venueName: 'The Metropolitan Museum of Art',
            neighborhood: 'Upper East Side',
            priceMin: 0.0,
            priceMax: 30.0,
            description: 'Curator-led tour of the Egyptian collection. Free with museum admission.',
            sourceDomain: 'metmuseum.org',
            checksum: 'met_egypt',
            canonicalUrlHash: 'hash_met_egypt',
            imageUrl: 'https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=800',
        },
        {
            sourceUrl: 'https://www.sleep-no-more.com/tickets',
            title: 'Sleep No More - Immersive Macbeth',
            city: 'New York',
            startTime: daysFromNow(6, 19),
            category: EventCategory.THEATRE,
            venueName: 'The McKittrick Hotel',
            neighborhood: 'Chelsea',
            priceMin: 75.0,
            priceMax: 150.0,
            description: 'Explore 100+ rooms in this masked, choose-your-own-adventure Shakespeare experience.',
            sourceDomain: 'sleep-no-more.com',
            checksum: 'sleep_no_more',
            canonicalUrlHash: 'hash_sleepnomore',
            imageUrl: 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=800',
        },
        {
            sourceUrl: 'https://www.bam.org/whats-on/dance-performance',
            title: 'Alvin Ailey American Dance Theater',
            city: 'New York',
            startTime: daysFromNow(13, 19),
            category: EventCategory.DANCE,
            venueName: 'Brooklyn Academy of Music',
            neighborhood: 'Fort Greene',
            priceMin: 30.0,
            priceMax: 95.0,
            description: 'Iconic modern dance company performs Revelations and new works.',
            sourceDomain: 'bam.org',
            checksum: 'ailey_bam',
            canonicalUrlHash: 'hash_ailey',
            imageUrl: 'https://images.unsplash.com/photo-1508807526345-15e9b5f4eaff?w=800',
        },
        {
            sourceUrl: 'https://www.publictheater.org/shakespeare-park',
            title: 'Shakespeare in the Park - Free Performance',
            city: 'New York',
            startTime: daysFromNow(18, 20),
            category: EventCategory.THEATRE,
            venueName: 'Delacorte Theater',
            neighborhood: 'Central Park',
            priceMin: 0.0,
            priceMax: 0.0,
            description: 'Free tickets distributed daily. A Midsummer Night\'s Dream starring Oscar Isaac.',
            sourceDomain: 'publictheater.org',
            checksum: 'shakespeare_park',
            canonicalUrlHash: 'hash_shakespeare',
            imageUrl: 'https://images.unsplash.com/photo-1507924538820-ede94a04019d?w=800',
        },
        {
            sourceUrl: 'https://www.prospectpark.org/alliance/programs/fitness/yoga',
            title: 'Free Outdoor Yoga in Prospect Park',
            city: 'New York',
            startTime: daysFromNow(1, 8),
            category: EventCategory.SPORTS,
            venueName: 'Prospect Park',
            neighborhood: 'Park Slope',
            priceMin: 0.0,
            priceMax: 0.0,
            description: 'All-levels vinyasa flow. Bring your own mat. Rain cancels.',
            sourceDomain: 'prospectpark.org',
            checksum: 'yoga_prospect',
            canonicalUrlHash: 'hash_yoga_prospect',
            imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
        },
        {
            sourceUrl: 'https://www.nba.com/nets/tickets',
            title: 'Brooklyn Nets vs Boston Celtics',
            city: 'New York',
            startTime: daysFromNow(16, 19),
            category: EventCategory.SPORTS,
            venueName: 'Barclays Center',
            neighborhood: 'Downtown Brooklyn',
            priceMin: 45.0,
            priceMax: 250.0,
            description: 'NBA Eastern Conference showdown. Tickets selling fast!',
            sourceDomain: 'barclayscenter.com',
            checksum: 'nets_celtics',
            canonicalUrlHash: 'hash_nets_celtics',
            imageUrl: 'https://images.unsplash.com/photo-1504450758481-7338eba7524a?w=800',
        },
        {
            sourceUrl: 'https://www.nyrr.org/races/brooklyn-half',
            title: 'NYRR Brooklyn Half Marathon',
            city: 'New York',
            startTime: daysFromNow(21, 7),
            category: EventCategory.SPORTS,
            venueName: 'Prospect Park to Coney Island',
            neighborhood: 'Brooklyn',
            priceMin: 85.0,
            priceMax: 125.0,
            description: '13.1 miles through Brooklyn. Registration includes race shirt and finisher medal.',
            sourceDomain: 'nyrr.org',
            checksum: 'brooklyn_half',
            canonicalUrlHash: 'hash_brooklyn_half',
            imageUrl: 'https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=800',
        },
        {
            sourceUrl: 'https://www.meetup.com/ny-tech-meetup/startup-pitch-night',
            title: 'NY Tech Meetup - Startup Pitch Night',
            city: 'New York',
            startTime: daysFromNow(4, 18),
            category: EventCategory.NETWORKING,
            venueName: 'NYU Tandon School of Engineering',
            neighborhood: 'Downtown Brooklyn',
            priceMin: 0.0,
            priceMax: 15.0,
            description: '8 startups pitch, followed by networking. Free pizza and beer.',
            sourceDomain: 'meetup.com',
            checksum: 'ny_tech_pitch',
            canonicalUrlHash: 'hash_nytech',
            imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
        },
        {
            sourceUrl: 'https://www.generalassemb.ly/education/javascript-workshop',
            title: 'Free JavaScript Workshop for Beginners',
            city: 'New York',
            startTime: daysFromNow(10, 18),
            category: EventCategory.EDUCATION,
            venueName: 'General Assembly',
            neighborhood: 'Flatiron',
            priceMin: 0.0,
            priceMax: 0.0,
            description: 'Learn the basics of JavaScript in 3 hours. Laptops provided.',
            sourceDomain: 'generalassemb.ly',
            checksum: 'ga_js_workshop',
            canonicalUrlHash: 'hash_ga_js',
            imageUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800',
        },
        {
            sourceUrl: 'https://www.powerhouse-arena.com/book-launch-party',
            title: 'Book Launch Party: NYC Memoir Night',
            city: 'New York',
            startTime: daysFromNow(7, 19),
            category: EventCategory.BOOK_CLUB,
            venueName: 'Powerhouse Arena',
            neighborhood: 'DUMBO',
            priceMin: 0.0,
            priceMax: 30.0,
            description: 'Author reading, Q&A, and book signing. Wine and cheese reception.',
            sourceDomain: 'powerhouse-arena.com',
            checksum: 'powerhouse_memoir',
            canonicalUrlHash: 'hash_powerhouse',
            imageUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800',
        },
        {
            sourceUrl: 'https://www.houseofyes.org/events/cirque-spectacular',
            title: 'House of Yes: Cirque du Spectacular',
            city: 'New York',
            startTime: daysFromNow(9, 22),
            category: EventCategory.DANCE,
            venueName: 'House of Yes',
            neighborhood: 'Bushwick',
            priceMin: 20.0,
            priceMax: 35.0,
            description: 'Acrobatic performances, burlesque, DJs, and immersive art. Dress to impress.',
            sourceDomain: 'houseofyes.org',
            checksum: 'houseofyes_cirque',
            canonicalUrlHash: 'hash_hoy_cirque',
            imageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800',
        },
        {
            sourceUrl: 'https://www.elsewherebrooklyn.com/events/rooftop-party',
            title: 'Elsewhere Rooftop - Summer Sunset Party',
            city: 'New York',
            startTime: daysFromNow(12, 17),
            category: EventCategory.MUSIC,
            venueName: 'Elsewhere',
            neighborhood: 'Bushwick',
            priceMin: 15.0,
            priceMax: 25.0,
            description: 'Rooftop DJs, skyline views, craft cocktails. 21+',
            sourceDomain: 'elsewherebrooklyn.com',
            checksum: 'elsewhere_rooftop',
            canonicalUrlHash: 'hash_elsewhere_roof',
            imageUrl: 'https://images.unsplash.com/photo-1472653816316-3ad6f10a6592?w=800',
        },
        {
            sourceUrl: 'https://www.output-club.com/techno-night',
            title: 'Output: Techno Night with Amelie Lens',
            city: 'New York',
            startTime: daysFromNow(17, 23),
            category: EventCategory.MUSIC,
            venueName: 'Avant Gardner',
            neighborhood: 'East Williamsburg',
            priceMin: 30.0,
            priceMax: 50.0,
            description: 'World-class techno DJ. Immersive sound system. No photos policy.',
            sourceDomain: 'avantgardner.com',
            checksum: 'output_amelie',
            canonicalUrlHash: 'hash_amelie',
            imageUrl: 'https://images.unsplash.com/photo-1571266028243-d220c6e96e58?w=800',
        },
        {
            sourceUrl: 'https://www.bronxzoo.com/summer-nights',
            title: 'Bronx Zoo Summer Nights',
            city: 'New York',
            startTime: daysFromNow(14, 18),
            category: EventCategory.FAMILY,
            venueName: 'Bronx Zoo',
            neighborhood: 'Bronx',
            priceMin: 20.0,
            priceMax: 40.0,
            description: 'Extended hours, live music, animal encounters. Kids under 3 free.',
            sourceDomain: 'bronxzoo.com',
            checksum: 'bronxzoo_summer',
            canonicalUrlHash: 'hash_bronxzoo',
            imageUrl: 'https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=800',
        },
        {
            sourceUrl: 'https://www.nycgovparks.org/movies-under-stars',
            title: 'Movies Under the Stars: The Lion King',
            city: 'New York',
            startTime: daysFromNow(11, 20),
            category: EventCategory.FILM,
            venueName: 'Bryant Park',
            neighborhood: 'Midtown',
            priceMin: 0.0,
            priceMax: 0.0,
            description: 'Free outdoor movie. Arrive early for blanket space. Food vendors on-site.',
            sourceDomain: 'bryantpark.org',
            checksum: 'bryant_lionking',
            canonicalUrlHash: 'hash_bryant_lk',
            imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800',
        },
        {
            sourceUrl: 'https://www.childrensmuseumofmanhattan.org/family-saturday',
            title: 'Family Saturday: Science Explorers',
            city: 'New York',
            startTime: daysFromNow(2, 10),
            category: EventCategory.EDUCATION,
            venueName: 'Children\'s Museum of Manhattan',
            neighborhood: 'Upper West Side',
            priceMin: 15.0,
            priceMax: 18.0,
            description: 'Hands-on science experiments for kids 5-10. Parents free with child ticket.',
            sourceDomain: 'cmom.org',
            checksum: 'cmom_science',
            canonicalUrlHash: 'hash_cmom',
            imageUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800',
        },
        {
            sourceUrl: 'https://www.urbanspaceNY.com/madison-square-market',
            title: 'Mad. Sq. Eats - Summer Food Market',
            city: 'New York',
            startTime: daysFromNow(1, 12),
            category: EventCategory.FOOD,
            venueName: 'Madison Square Park',
            neighborhood: 'Flatiron',
            priceMin: 0.0,
            priceMax: 0.0,
            description: '30+ food vendors, daily 11am-9pm. Free entry, pay per dish.',
            sourceDomain: 'urbanspacenyc.com',
            checksum: 'mad_sq_eats',
            canonicalUrlHash: 'hash_madsq',
            imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
        },
        {
            sourceUrl: 'https://www.brooklynflea.com/markets/dumbo/',
            title: 'Brooklyn Flea Market - DUMBO',
            city: 'New York',
            startTime: daysFromNow(3, 10),
            category: EventCategory.SHOPPING,
            venueName: 'Pearl Plaza',
            neighborhood: 'DUMBO',
            priceMin: 0.0,
            priceMax: 0.0,
            description: 'Vintage clothing, antiques, handmade goods. 100+ vendors every Sunday.',
            sourceDomain: 'brooklynflea.com',
            checksum: 'bkflea_dumbo',
            canonicalUrlHash: 'hash_bkflea',
            imageUrl: 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=800',
        },
        {
            sourceUrl: 'https://www.theway-station.com/trivia-night',
            title: 'Doctor Who Trivia Night at The Way Station',
            city: 'New York',
            startTime: daysFromNow(8, 20),
            category: EventCategory.SOCIAL,
            venueName: 'The Way Station',
            neighborhood: 'Prospect Heights',
            priceMin: 5.0,
            priceMax: 10.0,
            description: 'Sci-fi themed bar with Doctor Who trivia. Winning team gets $50 bar tab.',
            sourceDomain: 'theway-station.com',
            checksum: 'waystation_trivia',
            canonicalUrlHash: 'hash_waystation',
            imageUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800',
        },
        {
            sourceUrl: 'https://www.conyisland.com/programs/fireworks',
            title: 'Coney Island Friday Night Fireworks',
            city: 'New York',
            startTime: daysFromNow(5, 21),
            category: EventCategory.COMMUNITY,
            venueName: 'Coney Island Beach',
            neighborhood: 'Coney Island',
            priceMin: 0.0,
            priceMax: 0.0,
            description: 'Weekly fireworks show over the ocean. Boardwalk amusements open late.',
            sourceDomain: 'coneyisland.com',
            checksum: 'coney_fireworks',
            canonicalUrlHash: 'hash_coney_fire',
            imageUrl: 'https://images.unsplash.com/photo-1533567606119-4b2eb0857d15?w=800',
        },
        {
            sourceUrl: 'https://www.sleepnomore.com/dinner-show',
            title: 'Immersive Dinner Theater - The Grand Banquet',
            city: 'New York',
            startTime: daysFromNow(19, 19),
            category: EventCategory.THEATRE,
            venueName: 'The McKittrick Hotel',
            neighborhood: 'Chelsea',
            priceMin: 150.0,
            priceMax: 200.0,
            description: '5-course meal with theatrical performance throughout. Limited to 40 guests.',
            sourceDomain: 'mckittrickhotel.com',
            checksum: 'grand_banquet',
            canonicalUrlHash: 'hash_banquet',
            imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
        },
    ];
    console.log(`📅 Creating ${comprehensiveEvents.length} diverse events...\n`);
    let createdCount = 0;
    for (const event of comprehensiveEvents) {
        try {
            await prisma.event.upsert({
                where: {
                    unique_event: {
                        canonicalUrlHash: event.canonicalUrlHash,
                        startTime: event.startTime,
                    },
                },
                update: {},
                create: event,
            });
            createdCount++;
            if (createdCount % 10 === 0) {
                console.log(`   ✓ Created ${createdCount} events...`);
            }
        }
        catch (error) {
            console.warn(`   ⚠ Skipped duplicate: ${event.title}`);
        }
    }
    console.log(`\n✅ Successfully seeded ${createdCount} events!\n`);
    console.log('📊 Event Breakdown:');
    const categoryCounts = comprehensiveEvents.reduce((acc, event) => {
        acc[event.category] = (acc[event.category] || 0) + 1;
        return acc;
    }, {});
    Object.entries(categoryCounts).forEach(([category, count]) => {
        console.log(`   ${category}: ${count} events`);
    });
    console.log('\n🎉 Comprehensive seed complete! Database ready for production.');
}
main()
    .catch((e) => {
    console.error('❌ Error seeding:', e);
    process.exit(1);
})
    .finally(async () => {
    await prisma.$disconnect();
});
//# sourceMappingURL=comprehensive-seed.js.map