import { NextResponse } from 'next/server';

const MULTI_CITY_EVENTS = [
  // San Francisco Events
  {
    sourceUrl: 'https://test.com/sf-jazz-festival',
    title: 'SF Jazz Festival at SFJAZZ Center',
    subtitle: 'Annual Jazz Celebration',
    description: 'Three days of world-class jazz performances',
    category: 'MUSIC',
    organizer: 'SFJAZZ',
    venueName: 'SFJAZZ Center',
    address: '201 Franklin St, San Francisco, CA 94102',
    neighborhood: 'Hayes Valley',
    city: 'San Francisco',
    lat: 37.7765,
    lon: -122.4216,
    startTime: new Date('2025-11-15T19:00:00-08:00'),
    endTime: new Date('2025-11-15T22:00:00-08:00'),
    timezone: 'America/Los_Angeles',
    priceMin: 45,
    priceMax: 95,
    currency: 'USD',
    tags: ['jazz', 'festival', 'music'],
    imageUrl: null,
    bookingUrl: 'https://test.com/sf-jazz-tickets',
    accessibility: ['wheelchair-accessible'],
    sourceDomain: 'test.com',
  },
  {
    sourceUrl: 'https://test.com/sf-food-tour',
    title: 'Mission District Food Tour',
    subtitle: 'Taste of San Francisco',
    description: 'Explore the best tacos, burritos, and street food in the Mission',
    category: 'FOOD',
    organizer: 'SF Food Tours',
    venueName: 'Mission District',
    address: 'Mission St & 16th St, San Francisco, CA 94110',
    neighborhood: 'Mission',
    city: 'San Francisco',
    lat: 37.7647,
    lon: -122.4194,
    startTime: new Date('2025-11-12T11:00:00-08:00'),
    endTime: new Date('2025-11-12T14:00:00-08:00'),
    timezone: 'America/Los_Angeles',
    priceMin: 75,
    priceMax: 75,
    currency: 'USD',
    tags: ['food', 'tour', 'mexican'],
    imageUrl: null,
    bookingUrl: 'https://test.com/sf-food-tour-tickets',
    accessibility: ['walking-required'],
    sourceDomain: 'test.com',
  },

  // Los Angeles Events
  {
    sourceUrl: 'https://test.com/la-comedy-store',
    title: 'Comedy Night at The Comedy Store',
    subtitle: 'Stand-Up Comedy Showcase',
    description: 'Catch rising stars and comedy legends on the Sunset Strip',
    category: 'COMEDY',
    organizer: 'The Comedy Store',
    venueName: 'The Comedy Store',
    address: '8433 Sunset Blvd, West Hollywood, CA 90069',
    neighborhood: 'West Hollywood',
    city: 'Los Angeles',
    lat: 34.0979,
    lon: -118.3767,
    startTime: new Date('2025-11-10T20:00:00-08:00'),
    endTime: new Date('2025-11-10T22:30:00-08:00'),
    timezone: 'America/Los_Angeles',
    priceMin: 25,
    priceMax: 40,
    currency: 'USD',
    minAge: 21,
    tags: ['comedy', 'stand-up', 'nightlife'],
    imageUrl: null,
    bookingUrl: 'https://test.com/la-comedy-tickets',
    accessibility: ['21+', 'wheelchair-accessible'],
    sourceDomain: 'test.com',
  },
  {
    sourceUrl: 'https://test.com/la-beach-yoga',
    title: 'Sunrise Yoga at Venice Beach',
    subtitle: 'Free Community Yoga',
    description: 'Start your day with yoga on the beach with ocean views',
    category: 'FITNESS',
    organizer: 'Venice Beach Yoga',
    venueName: 'Venice Beach',
    address: 'Venice Beach Boardwalk, Venice, CA 90291',
    neighborhood: 'Venice',
    city: 'Los Angeles',
    lat: 33.9850,
    lon: -118.4695,
    startTime: new Date('2025-11-13T06:30:00-08:00'),
    endTime: new Date('2025-11-13T07:30:00-08:00'),
    timezone: 'America/Los_Angeles',
    priceMin: 0,
    priceMax: 0,
    currency: 'USD',
    tags: ['yoga', 'fitness', 'free', 'outdoor'],
    imageUrl: null,
    bookingUrl: null,
    accessibility: ['outdoor', 'free'],
    sourceDomain: 'test.com',
  },

  // Chicago Events
  {
    sourceUrl: 'https://test.com/chicago-blues-festival',
    title: 'Chicago Blues Festival',
    subtitle: 'Free Blues Music Festival',
    description: 'Three days of authentic Chicago blues in Millennium Park',
    category: 'MUSIC',
    organizer: 'City of Chicago',
    venueName: 'Millennium Park',
    address: '201 E Randolph St, Chicago, IL 60602',
    neighborhood: 'The Loop',
    city: 'Chicago',
    lat: 41.8826,
    lon: -87.6226,
    startTime: new Date('2025-11-16T16:00:00-06:00'),
    endTime: new Date('2025-11-16T21:00:00-06:00'),
    timezone: 'America/Chicago',
    priceMin: 0,
    priceMax: 0,
    currency: 'USD',
    tags: ['blues', 'festival', 'free', 'music'],
    imageUrl: null,
    bookingUrl: null,
    accessibility: ['outdoor', 'free', 'wheelchair-accessible'],
    sourceDomain: 'test.com',
  },
  {
    sourceUrl: 'https://test.com/chicago-deep-dish',
    title: 'Deep Dish Pizza Making Class',
    subtitle: 'Learn to Make Chicago-Style Pizza',
    description: 'Hands-on class teaching authentic Chicago deep dish techniques',
    category: 'FOOD',
    organizer: 'Chicago Culinary School',
    venueName: 'Chicago Culinary School',
    address: '225 W Hubbard St, Chicago, IL 60654',
    neighborhood: 'River North',
    city: 'Chicago',
    lat: 41.8899,
    lon: -87.6363,
    startTime: new Date('2025-11-14T18:00:00-06:00'),
    endTime: new Date('2025-11-14T20:30:00-06:00'),
    timezone: 'America/Chicago',
    priceMin: 85,
    priceMax: 85,
    currency: 'USD',
    tags: ['food', 'cooking', 'pizza', 'class'],
    imageUrl: null,
    bookingUrl: 'https://test.com/chicago-pizza-class',
    accessibility: ['indoor'],
    sourceDomain: 'test.com',
  },

  // Boston Events
  {
    sourceUrl: 'https://test.com/boston-symphony',
    title: 'Boston Symphony Orchestra at Symphony Hall',
    subtitle: 'Beethoven Symphony No. 9',
    description: 'Experience Beethoven\'s masterpiece performed by the BSO',
    category: 'MUSIC',
    organizer: 'Boston Symphony Orchestra',
    venueName: 'Symphony Hall',
    address: '301 Massachusetts Ave, Boston, MA 02115',
    neighborhood: 'Back Bay',
    city: 'Boston',
    lat: 42.3427,
    lon: -71.0851,
    startTime: new Date('2025-11-17T19:30:00-05:00'),
    endTime: new Date('2025-11-17T22:00:00-05:00'),
    timezone: 'America/New_York',
    priceMin: 55,
    priceMax: 150,
    currency: 'USD',
    tags: ['classical', 'orchestra', 'symphony'],
    imageUrl: null,
    bookingUrl: 'https://test.com/bso-tickets',
    accessibility: ['wheelchair-accessible'],
    sourceDomain: 'test.com',
  },
  {
    sourceUrl: 'https://test.com/boston-harbor-run',
    title: 'Boston Harbor 5K Run',
    subtitle: 'Waterfront Running Event',
    description: 'Scenic 5K along the Boston Harbor with city skyline views',
    category: 'FITNESS',
    organizer: 'Boston Running Club',
    venueName: 'Boston Harborwalk',
    address: 'Fan Pier, Boston, MA 02210',
    neighborhood: 'Seaport',
    city: 'Boston',
    lat: 42.3539,
    lon: -71.0443,
    startTime: new Date('2025-11-11T08:00:00-05:00'),
    endTime: new Date('2025-11-11T10:00:00-05:00'),
    timezone: 'America/New_York',
    priceMin: 30,
    priceMax: 30,
    currency: 'USD',
    tags: ['running', '5k', 'fitness', 'outdoor'],
    imageUrl: null,
    bookingUrl: 'https://test.com/boston-5k',
    accessibility: ['outdoor'],
    sourceDomain: 'test.com',
  },
];

export async function POST() {
  return NextResponse.json(
    {
      error: 'Seed ingestion now runs inside the worker. /api/seed-multi-city is disabled.',
    },
    { status: 410 }
  );
}
