import { z } from 'zod';
export * from './lens';
export const EventCategorySchema = z.enum([
    'MUSIC',
    'COMEDY',
    'THEATRE',
    'FITNESS',
    'DANCE',
    'ARTS',
    'FOOD',
    'NETWORKING',
    'FAMILY',
    'OTHER',
]);
export const EventSchema = z.object({
    source_url: z.string().url(),
    title: z.string().min(1),
    subtitle: z.string().optional(),
    description: z.string().optional(),
    category: z.enum([
        'music',
        'comedy',
        'theatre',
        'fitness',
        'dance',
        'arts',
        'food',
        'networking',
        'family',
        'other',
    ]).optional(),
    organizer: z.string().optional(),
    venue_name: z.string().optional(),
    address: z.string().optional(),
    neighborhood: z.string().optional(),
    city: z.string(),
    lat: z.number().optional(),
    lon: z.number().optional(),
    start_time: z.string().datetime(),
    end_time: z.string().datetime().optional(),
    timezone: z.string().optional(),
    price_min: z.number().optional(),
    price_max: z.number().optional(),
    currency: z.string().optional(),
    min_age: z.number().int().optional(),
    tags: z.array(z.string()).optional().default([]),
    image_url: z.string().url().optional(),
    booking_url: z.string().url().optional(),
    accessibility: z.array(z.string()).optional().default([]),
    source_domain: z.string().optional(),
    checksum: z.string().optional(),
    updated_at: z.string().datetime().optional(),
});
export const FirecrawlWebhookSchema = z.object({
    success: z.boolean(),
    data: z.object({
        markdown: z.string().optional(),
        html: z.string().optional(),
        metadata: z.object({
            title: z.string().optional(),
            description: z.string().optional(),
            url: z.string(),
        }).passthrough(),
    }),
    jobId: z.string().optional(),
});
export const ApifyWebhookSchema = z.object({
    eventType: z.string(),
    eventData: z.object({
        actorRunId: z.string(),
    }).passthrough(),
    resource: z.object({
        id: z.string(),
        defaultDatasetId: z.string().optional(),
    }).passthrough(),
});
export const EventsSearchParamsSchema = z.object({
    q: z.string().optional(),
    city: z.string().optional(),
    category: z.string().optional(),
    date_from: z.string().optional(),
    date_to: z.string().optional(),
    price_max: z.number().optional(),
    neighborhood: z.string().optional(),
    page: z.number().int().positive().default(1),
    limit: z.number().int().positive().max(100).default(20),
});
export const TypesenseEventSchema = z.object({
    id: z.string(),
    title: z.string(),
    subtitle: z.string().optional(),
    description: z.string().optional(),
    category: z.string().optional(),
    venue_name: z.string().optional(),
    address: z.string().optional(),
    neighborhood: z.string().optional(),
    city: z.string(),
    lat: z.number().optional(),
    lon: z.number().optional(),
    start_time: z.number(),
    end_time: z.number().optional(),
    price_min: z.number().optional(),
    price_max: z.number().optional(),
    tags: z.array(z.string()),
    image_url: z.string().optional(),
    booking_url: z.string().optional(),
    source_domain: z.string(),
});
export const IngestRequestSchema = z.object({
    sourceId: z.string().optional(),
    url: z.string().url(),
    html: z.string().optional(),
    markdown: z.string().optional(),
    city: z.string().default('New York'),
});
//# sourceMappingURL=index.js.map